# Error Analysis for JO's Bike Shop Multi-Turn Chatbot

This notebook implements the error analysis methodology described in `error_analysis_plan.md` using open coding and axial coding techniques.

## Part 1: Define Dimensions & Generate Initial Queries

### 1.1 Identified Dimensions

**Dimension 1: Primary Intent** (conversation_mode)
- `shop_info`, `product_inquiry`, `book_appointment`, `maintenance_tips`, `policy_question`, `recall_booking`, `what_can_you_do`

**Dimension 2: Information Completeness** (booking_completeness)
- `complete_upfront`, `partial_info`, `minimal_info`, `no_info`

**Dimension 3: Conversation Complexity** (interaction_pattern)
- `single_turn`, `multi_turn_linear`, `multi_turn_complex`, `mixed_intent`

**Dimension 4: User Behavior Pattern** (user_behavior)
- `cooperative`, `conversational`, `corrective`, `distracted`, `canceling`

### 1.2 Generate Unique Combinations (Tuples)

Using an LLM to generate diverse test scenario combinations.

In [1]:
# Fix OpenTelemetry TracerProvider conflict
import os

# Disable OpenTelemetry to prevent TracerProvider override conflicts
os.environ["OTEL_SDK_DISABLED"] = "true"
os.environ["OTEL_PYTHON_CONFIGURATOR"] = "default"

print("✓ OpenTelemetry disabled to prevent tracing conflicts")

✓ OpenTelemetry disabled to prevent tracing conflicts

In [2]:
# Install ipywidgets for Jupyter rich display support
! pip install ipywidgets -q

In [3]:
import os
from openai import OpenAI
import nest_asyncio
nest_asyncio.apply()

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

### Setup & Dependencies

We'll use OpenAI's GPT-4o to generate test scenarios and queries. The `nest_asyncio` library allows us to run async code in Jupyter notebooks.

In [4]:
# Prompt for generating test scenario combinations
combination_prompt = """You are helping create test scenarios for a bike shop chatbot that handles multi-turn conversations. 

Generate 20 unique test scenario combinations using these dimensions:

1. Primary Intent: shop_info, product_inquiry, book_appointment, maintenance_tips, policy_question, recall_booking, what_can_you_do
2. Information Completeness: complete_upfront, partial_info, minimal_info, no_info
3. Interaction Pattern: single_turn, multi_turn_linear, multi_turn_complex, mixed_intent
4. User Behavior: cooperative, conversational, corrective, distracted, canceling

For each combination, output as a tuple: (primary_intent, completeness, interaction_pattern, user_behavior)

Ensure diverse coverage:
- Include at least 5 book_appointment scenarios (this is the main multi-turn feature)
- Include at least 2 recall_booking scenarios
- Include at least 3 scenarios with corrective or distracted behavior
- Vary the interaction patterns to test different conversation flows

Output format: One tuple per line, e.g.:
(book_appointment, partial_info, multi_turn_linear, cooperative)

Return ONLY the tuples, one per line, no additional text or explanation."""

# Call OpenAI API to generate combinations
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "system", "content": "You are a helpful assistant that generates test scenarios for chatbot evaluation."},
        {"role": "user", "content": combination_prompt}
    ],
    temperature=0.8,  # Higher temperature for more diverse combinations
)

# Extract and display the generated combinations
generated_combinations = response.choices[0].message.content
print(generated_combinations)

(shop_info, complete_upfront, single_turn, cooperative)
(product_inquiry, partial_info, multi_turn_linear, conversational)
(book_appointment, minimal_info, multi_turn_complex, cooperative)
(maintenance_tips, no_info, single_turn, corrective)
(policy_question, complete_upfront, multi_turn_linear, distracted)
(recall_booking, partial_info, multi_turn_complex, cooperative)
(what_can_you_do, no_info, mixed_intent, conversational)
(book_appointment, complete_upfront, multi_turn_linear, cooperative)
(maintenance_tips, partial_info, multi_turn_linear, cooperative)
(book_appointment, no_info, multi_turn_complex, distracted)
(product_inquiry, minimal_info, mixed_intent, corrective)
(policy_question, partial_info, single_turn, cooperative)
(recall_booking, minimal_info, multi_turn_linear, corrective)
(book_appointment, minimal_info, multi_turn_linear, canceling)
(what_can_you_do, complete_upfront, single_turn, cooperative)
(shop_info, no_info, mixed_intent, distracted)
(book_appointment, partial_info, multi_turn_linear, cooperative)
(product_inquiry, complete_upfront, multi_turn_complex, cooperative)
(maintenance_tips, minimal_info, mixed_intent, conversational)
(book_appointment, partial_info, multi_turn_complex, cooperative)

In [5]:
# Parse the combinations into a structured list
import re

# Extract tuples from the text
tuple_pattern = r'\([^)]+\)'
tuples_raw = re.findall(tuple_pattern, generated_combinations)

# Parse each tuple
test_scenarios = []
for tuple_str in tuples_raw:
    # Remove parentheses and split by comma
    parts = tuple_str.strip('()').split(', ')
    if len(parts) == 4:
        test_scenarios.append({
            'primary_intent': parts[0],
            'completeness': parts[1],
            'interaction_pattern': parts[2],
            'user_behavior': parts[3],
            'tuple': tuple_str
        })

print(f"Generated {len(test_scenarios)} test scenarios:\n")
for i, scenario in enumerate(test_scenarios, 1):
    print(f"{i}. {scenario['tuple']}")

Generated 20 test scenarios:

1. (shop_info, complete_upfront, single_turn, cooperative)
2. (product_inquiry, partial_info, multi_turn_linear, conversational)
3. (book_appointment, minimal_info, multi_turn_complex, cooperative)
4. (maintenance_tips, no_info, single_turn, corrective)
5. (policy_question, complete_upfront, multi_turn_linear, distracted)
6. (recall_booking, partial_info, multi_turn_complex, cooperative)
7. (what_can_you_do, no_info, mixed_intent, conversational)
8. (book_appointment, complete_upfront, multi_turn_linear, cooperative)
9. (maintenance_tips, partial_info, multi_turn_linear, cooperative)
10. (book_appointment, no_info, multi_turn_complex, distracted)
11. (product_inquiry, minimal_info, mixed_intent, corrective)
12. (policy_question, partial_info, single_turn, cooperative)
13. (recall_booking, minimal_info, multi_turn_linear, corrective)
14. (book_appointment, minimal_info, multi_turn_linear, canceling)
15. (what_can_you_do, complete_upfront, single_turn, cooperative)
16. (shop_info, no_info, mixed_intent, distracted)
17. (book_appointment, partial_info, multi_turn_linear, cooperative)
18. (product_inquiry, complete_upfront, multi_turn_complex, cooperative)
19. (maintenance_tips, minimal_info, mixed_intent, conversational)
20. (book_appointment, partial_info, multi_turn_complex, cooperative)

In [6]:
# Save the generated combinations to a file for future reference
import json

output_file = 'test_scenario_combinations.json'

with open(output_file, 'w') as f:
    json.dump(test_scenarios, f, indent=2)

print(f"\n✓ Saved {len(test_scenarios)} test scenarios to {output_file}")

✓ Saved 20 test scenarios to test_scenario_combinations.json

#### Analyze Scenario Distribution

Let's examine how our generated scenarios are distributed across the different dimensions. This helps ensure we have good coverage for testing.

In [7]:
# Analyze the distribution of scenarios
import pandas as pd

df = pd.DataFrame(test_scenarios)

print("Distribution by Primary Intent:")
print(df['primary_intent'].value_counts())
print("\nDistribution by Information Completeness:")
print(df['completeness'].value_counts())
print("\nDistribution by Interaction Pattern:")
print(df['interaction_pattern'].value_counts())
print("\nDistribution by User Behavior:")
print(df['user_behavior'].value_counts())

Distribution by Primary Intent:
primary_intent
book_appointment    6
product_inquiry     3
maintenance_tips    3
shop_info           2
policy_question     2
recall_booking      2
what_can_you_do     2
Name: count, dtype: int64

Distribution by Information Completeness:
completeness
partial_info        6
complete_upfront    5
minimal_info        5
no_info             4
Name: count, dtype: int64

Distribution by Interaction Pattern:
interaction_pattern
multi_turn_linear     7
multi_turn_complex    5
single_turn           4
mixed_intent          4
Name: count, dtype: int64

Distribution by User Behavior:
user_behavior
cooperative       10
conversational     3
corrective         3
distracted         3
canceling          1
Name: count, dtype: int64

In [8]:
df.drop(columns=['tuple'])

      primary_intent      completeness interaction_pattern   user_behavior
0          shop_info  complete_upfront         single_turn     cooperative
1    product_inquiry      partial_info   multi_turn_linear  conversational
2   book_appointment      minimal_info  multi_turn_complex     cooperative
3   maintenance_tips           no_info         single_turn      corrective
4    policy_question  complete_upfront   multi_turn_linear      distracted
5     recall_booking      partial_info  multi_turn_complex     cooperative
6    what_can_you_do           no_info        mixed_intent  conversational
7   book_appointment  complete_upfront   multi_turn_linear     cooperative
8   maintenance_tips      partial_info   multi_turn_linear     cooperative
9   book_appointment           no_info  multi_turn_complex      distracted
10   product_inquiry      minimal_info        mixed_intent      corrective
11   policy_question      partial_info         single_turn     cooperative
12    recall_booking      minimal_info   multi_turn_linear      corrective
13  book_appointment      minimal_info   multi_turn_linear       canceling
14   what_can_you_do  complete_upfront         single_turn     cooperative
15         shop_info           no_info        mixed_intent      distracted
16  book_appointment      partial_info   multi_turn_linear     cooperative
17   product_inquiry  complete_upfront  multi_turn_complex     cooperative
18  maintenance_tips      minimal_info        mixed_intent  conversational
19  book_appointment      partial_info  multi_turn_complex     cooperative

In [9]:
df[df['interaction_pattern'] == 'single_turn']

,primary_intent,completeness,interaction_pattern,user_behavior,tuple
0,shop_info,complete_upfront,single_turn,cooperative,"(shop_info, complete_upfront, single_turn, coo..."
3,maintenance_tips,no_info,single_turn,corrective,"(maintenance_tips, no_info, single_turn, corre..."
11,policy_question,partial_info,single_turn,cooperative,"(policy_question, partial_info, single_turn, c..."
14,what_can_you_do,complete_upfront,single_turn,cooperative,"(what_can_you_do, complete_upfront, single_tur..."

In [10]:
df[df['interaction_pattern'] == 'multi_turn_linear']

,primary_intent,completeness,interaction_pattern,user_behavior,tuple
1,product_inquiry,partial_info,multi_turn_linear,conversational,"(product_inquiry, partial_info, multi_turn_lin..."
4,policy_question,complete_upfront,multi_turn_linear,distracted,"(policy_question, complete_upfront, multi_turn..."
7,book_appointment,complete_upfront,multi_turn_linear,cooperative,"(book_appointment, complete_upfront, multi_tur..."
8,maintenance_tips,partial_info,multi_turn_linear,cooperative,"(maintenance_tips, partial_info, multi_turn_li..."
12,recall_booking,minimal_info,multi_turn_linear,corrective,"(recall_booking, minimal_info, multi_turn_line..."
13,book_appointment,minimal_info,multi_turn_linear,canceling,"(book_appointment, minimal_info, multi_turn_li..."
16,book_appointment,partial_info,multi_turn_linear,cooperative,"(book_appointment, partial_info, multi_turn_li..."

### 1.3 Separate Single-Turn and Multi-Turn Scenarios

We'll generate synthetic examples for two conversation types:
- **Single-Turn**: Simple query/response interactions
- **Multi-Turn**: Complex conversations with adaptive user simulation

Scenarios are automatically separated below:

In [11]:
# Separate scenarios into single-turn and multi-turn test types
# Single-Turn: simple, direct query/response (good for starting)
# Multi-Turn: complex patterns with adaptive user simulation

print("="*80)
print("SEPARATING SINGLE-TURN AND MULTI-TURN SCENARIOS")
print("="*80)
print("\nSingle-Turn Conversations:")
print("   - Focus: Simple query/response interactions")
print("   - Scenarios: single_turn interaction patterns only")
print("\nMulti-Turn Conversations:")
print("   - Focus: Complex conversations with adaptive user simulation")
print("   - Scenarios: multi_turn_linear, multi_turn_complex, mixed_intent patterns")
print("="*80 + "\n")

# Separate scenarios by conversation type
single_turn_scenarios = [s for s in test_scenarios if s['interaction_pattern'] == 'single_turn']
multi_turn_scenarios = [s for s in test_scenarios if s['interaction_pattern'] != 'single_turn']

print(f"✓ Single-turn scenarios: {len(single_turn_scenarios)}")
print(f"✓ Multi-turn scenarios: {len(multi_turn_scenarios)}")
print(f"✓ Total scenarios: {len(test_scenarios)}")

================================================================================
SEPARATING SINGLE-TURN AND MULTI-TURN SCENARIOS
================================================================================

Single-Turn Conversations:
   - Focus: Simple query/response interactions
   - Scenarios: single_turn interaction patterns only

Multi-Turn Conversations:
   - Focus: Complex conversations with adaptive user simulation
   - Scenarios: multi_turn_linear, multi_turn_complex, mixed_intent patterns
================================================================================

✓ Single-turn scenarios: 4
✓ Multi-turn scenarios: 16
✓ Total scenarios: 20

### 1.4 Generate Synthetic Examples

Generate appropriate synthetic examples for both conversation types.

In [12]:
# Generate simple single-turn queries
def generate_single_turn_examples(scenarios, examples_per_scenario=1):
    """
    Generate simple, realistic single-turn queries.
    
    Args:
        scenarios: List of scenario dictionaries
        examples_per_scenario: Number of example queries to generate per scenario (default: 1)
    
    Returns:
        List of query dictionaries with metadata
    """
    examples = []
    
    for scenario in scenarios:
        for example_num in range(examples_per_scenario):
            # Create a prompt to generate a realistic single-turn query
            query_prompt = f"""Generate a single, realistic user query for a bike shop chatbot.

Scenario details:
- Primary Intent: {scenario['primary_intent']}
- Information Completeness: {scenario['completeness']}
- User Behavior: {scenario['user_behavior']}

Requirements:
- Generate ONE natural language query that a real customer might ask
- Match the primary intent (e.g., shop_info = asking about hours/location)
- Match the completeness level:
  * complete_upfront: Include all necessary details in the query
  * partial_info: Include some but not all details
  * minimal_info: Very basic query with little detail
  * no_info: General question with no specifics
- Use natural, friendly tone for conversational behavior

Return ONLY the user query, nothing else. Make it sound natural and realistic."""

            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are an expert at creating realistic user queries for chatbot testing."},
                    {"role": "user", "content": query_prompt}
                ],
                temperature=0.8
            )
            
            user_query = response.choices[0].message.content.strip()
            
            examples.append({
                'conversation_type': 'single_turn',
                'scenario': scenario,
                'user_query': user_query,
                'expected_mode': scenario['primary_intent']
            })
    
    return examples


# Generate multi-turn conversation goals
def generate_multi_turn_examples(scenarios):
    """
    Generate conversation goals and initial queries for multi-turn scenarios.
    These will be used with adaptive user simulation.
    
    Args:
        scenarios: List of scenario dictionaries
    
    Returns:
        List of conversation goal dictionaries with metadata
    """
    examples = []
    
    for scenario in scenarios:
        # Create goal based on intent
        intent = scenario['primary_intent']
        if intent == 'book_appointment':
            goal = "Successfully book a service appointment by providing service type, date, and time"
        elif intent == 'shop_info':
            goal = "Get specific information about shop hours, location, or services"
        elif intent == 'product_inquiry':
            goal = "Learn about specific bikes or accessories and their availability"
        elif intent == 'maintenance_tips':
            goal = "Get practical advice on bike maintenance or care"
        elif intent == 'policy_question':
            goal = "Understand store policies regarding returns, warranties, or delivery"
        elif intent == 'recall_booking':
            goal = "Successfully recall or reference a previously made booking"
        else:
            goal = f"Complete a {intent} interaction successfully"
        
        # Generate initial query
        query_prompt = f"""Generate an initial user query to start a multi-turn conversation with a bike shop chatbot.

Scenario:
- Primary Intent: {scenario['primary_intent']}
- Information Completeness: {scenario['completeness']}
- User Behavior: {scenario['user_behavior']}
- User Goal: {goal}

Generate a realistic opening message that matches the completeness level and behavior.
Return ONLY the initial query, nothing else."""

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are an expert at creating realistic conversation starters."},
                {"role": "user", "content": query_prompt}
            ],
            temperature=0.8
        )
        
        initial_query = response.choices[0].message.content.strip()
        
        examples.append({
            'conversation_type': 'multi_turn',
            'scenario': scenario,
            'user_goal': goal,
            'initial_query': initial_query,
            'expected_mode': scenario['primary_intent']
        })
    
    return examples


print("✓ Single-turn and multi-turn generation functions defined")

✓ Single-turn and multi-turn generation functions defined

In [13]:
# Generate examples for both conversation types
all_synthetic_examples = {}

print("\n" + "="*80)
print("GENERATING SYNTHETIC EXAMPLES")
print("="*80 + "\n")

# Single-turn examples
print("📍 Generating single-turn queries...")
single_turn_examples = generate_single_turn_examples(single_turn_scenarios, examples_per_scenario=2)
all_synthetic_examples['single_turn'] = single_turn_examples
print(f"✓ Generated {len(single_turn_examples)} single-turn queries\n")

# Save single-turn examples
output_file_single = 'single_turn_synthetic_examples.json'
with open(output_file_single, 'w') as f:
    json.dump({
        'conversation_type': 'single_turn',
        'count': len(single_turn_examples),
        'examples': single_turn_examples
    }, f, indent=2)
print(f"✓ Saved to {output_file_single}\n")

# Multi-turn examples
print("📍 Generating multi-turn conversation goals...")
multi_turn_examples = generate_multi_turn_examples(multi_turn_scenarios)
all_synthetic_examples['multi_turn'] = multi_turn_examples
print(f"✓ Generated {len(multi_turn_examples)} multi-turn conversation goals\n")

# Save multi-turn examples
output_file_multi = 'multi_turn_synthetic_examples.json'
with open(output_file_multi, 'w') as f:
    json.dump({
        'conversation_type': 'multi_turn',
        'count': len(multi_turn_examples),
        'examples': multi_turn_examples
    }, f, indent=2)
print(f"✓ Saved to {output_file_multi}\n")

print("="*80)
print(f"TOTAL: {len(single_turn_examples) + len(multi_turn_examples)} examples generated")
print("="*80)

================================================================================
GENERATING SYNTHETIC EXAMPLES
================================================================================

📍 Generating single-turn queries...
✓ Generated 8 single-turn queries

✓ Saved to single_turn_synthetic_examples.json

📍 Generating multi-turn conversation goals...
✓ Generated 16 multi-turn conversation goals

✓ Saved to multi_turn_synthetic_examples.json

================================================================================
TOTAL: 24 examples generated
================================================================================

In [14]:
# Display sample examples from both conversation types
print("\n" + "="*80)
print("SAMPLE SYNTHETIC EXAMPLES")
print("="*80)

print("\n--- SINGLE-TURN SAMPLES ---\n")
for i, example in enumerate(all_synthetic_examples['single_turn'][:3], 1):
    print(f"{i}. Scenario: {example['scenario']['tuple']}")
    print(f"   Query: \"{example['user_query']}\"")
    print()

print("\n--- MULTI-TURN SAMPLES ---\n")
for i, example in enumerate(all_synthetic_examples['multi_turn'][:3], 1):
    print(f"{i}. Scenario: {example['scenario']['tuple']}")
    print(f"   Goal: {example['user_goal']}")
    print(f"   Initial Query: \"{example['initial_query']}\"")
    print()

================================================================================
SAMPLE SYNTHETIC EXAMPLES
================================================================================

--- SINGLE-TURN SAMPLES ---

1. Scenario: (shop_info, complete_upfront, single_turn, cooperative)
   Query: "Hi there! Could you please let me know your store hours and location? I'm planning to visit soon. Thanks!"

2. Scenario: (shop_info, complete_upfront, single_turn, cooperative)
   Query: ""Hi there! Could you please let me know your store hours and location? I'm planning to visit this weekend and want to make sure I have the right details. Thanks!""

3. Scenario: (maintenance_tips, no_info, single_turn, corrective)
   Query: "Oops, I meant to ask about bike maintenance tips. Can you help with that?"


--- MULTI-TURN SAMPLES ---

1. Scenario: (product_inquiry, partial_info, multi_turn_linear, conversational)
   Goal: Learn about specific bikes or accessories and their availability
   Initial Query: "Hi there! I'm interested in finding out more about mountain bikes. Could you tell me about the options you have and what accessories might be available for them?"

2. Scenario: (book_appointment, minimal_info, multi_turn_complex, cooperative)
   Goal: Successfully book a service appointment by providing service type, date, and time
   Initial Query: "Hi! I'd like to book an appointment for a bike service. Can you help me with that?"

3. Scenario: (policy_question, complete_upfront, multi_turn_linear, distracted)
   Goal: Understand store policies regarding returns, warranties, or delivery
   Initial Query: ""Hey, I was just looking into getting a bike from your shop, but I might have to step out soon. Could you quickly tell me about your return policy and any warranties or delivery options you offer?""

## Part 2: Error Analysis - Running Simulations

We'll use the synthetic examples generated in Part 1 for both single-turn and multi-turn conversations.

In [15]:
# Verify we have synthetic examples to test
if 'all_synthetic_examples' not in locals() or not all_synthetic_examples:
    raise ValueError("No synthetic examples found. Please run Part 1 first to generate examples.")

print("✓ Loaded synthetic examples from Part 1")
print(f"  Single-turn examples: {len(all_synthetic_examples['single_turn'])}")
print(f"  Multi-turn examples: {len(all_synthetic_examples['multi_turn'])}")
print(f"  Total examples: {len(all_synthetic_examples['single_turn']) + len(all_synthetic_examples['multi_turn'])}")

✓ Loaded synthetic examples from Part 1
  Single-turn examples: 8
  Multi-turn examples: 16
  Total examples: 24

### Test Execution Functions

We define two test functions:
- `run_single_turn_test`: Tests simple one-query-one-response interactions
- `run_multi_turn_test`: Uses DeepEval to simulate realistic multi-turn conversations where the synthetic user adapts based on bot responses

**Note**: In multi-turn tests, a "turn" means one complete user-assistant exchange (user sends a message, bot responds).

In [16]:
# Import Burr application
import sys
sys.path.append('..')

from application import application, TERMINAL_ACTIONS
import asyncio

print("✓ Burr application imported successfully")

✓ Burr application imported successfully

In [17]:
# Function to run a single-turn test
async def run_single_turn_test(example, test_id):
    """
    Run a single-turn test: submit query, get bot response.
    
    Args:
        example: Dictionary with scenario and user_query from synthetic_examples
        test_id: Unique identifier for this test
    
    Returns:
        Dictionary with test results
    """
    # Create fresh Burr application instance
    app = application(app_id=f"test_{test_id}")
    
    user_query = example['user_query']
    scenario = example['scenario']
    
    result = {
        'test_id': test_id,
        'scenario': scenario,
        'user_query': user_query,
        'bot_response': None,
        'action_taken': None,
        'state_snapshot': None,
        'success': False,
        'error': None
    }
    
    try:
        # Submit query to bot
        action, streaming_container = await app.astream_result(
            halt_after=TERMINAL_ACTIONS,
            inputs={"query": user_query}
        )
        
        # Collect streaming response
        response_parts = []
        async for item in streaming_container:
            response_parts.append(item.get('delta', ''))
        
        bot_response = ''.join(response_parts)
        
        # Get final state
        final_result, state = await streaming_container.get()
        
        # Update result
        result['bot_response'] = bot_response
        result['action_taken'] = action.name
        result['state_snapshot'] = {
            'mode': state.get('mode'),
            'in_appointment_flow': state.get('in_appointment_flow'),
            'appointment_data': state.get('appointment_data'),
            'safe': state.get('safe')
        }
        result['success'] = True
        print(f"Chat State: {state}")
        
    except Exception as e:
        result['error'] = str(e)
    
    return result

print("✓ Function defined: run_single_turn_test()")

✓ Function defined: run_single_turn_test()

In [18]:
async def run_multi_turn_test(example, test_id):
    """
    Run a multi-turn test using DeepEval's ConversationSimulator.
    Generates synthetic conversations based on scenario and user goal.
    
    Note: A "turn" = one user-assistant exchange (user message + bot response).
    
    Args:
        example: Dictionary with scenario, user_goal, and initial_query
        test_id: Unique identifier for this test
    
    Returns:
        Dictionary with test results including conversation turns
    """
    from deepeval.simulator import ConversationSimulator
    from deepeval.dataset import ConversationalGolden
    from deepeval.test_case import Turn
    from typing import List
    
    # Cache for maintaining conversation state
    _app_cache = {}
    
    # Model callback that wraps the Burr application
    async def burr_model_callback(input: str, turns: List[Turn], thread_id: str) -> Turn:
        """Wraps Burr app so DeepEval can interact with it."""
        # Reuse existing app for this conversation or create new one
        if thread_id not in _app_cache:
            _app_cache[thread_id] = application(app_id=f"{test_id}_{thread_id}")
        
        app = _app_cache[thread_id]
        
        _, streaming_container = await app.astream_result(
            halt_after=TERMINAL_ACTIONS,
            inputs={"query": input}
        )
        
        # Extract response from Burr's state
        _, state = await streaming_container.get()
        bot_message = state["response"]["content"]
        
        return Turn(role="assistant", content=bot_message)
    
    scenario = example['scenario']
    
    # Create scenario description from tuple dimensions
    scenario_desc = f"A user with {scenario['user_behavior']} behavior wants to {scenario['primary_intent'].replace('_', ' ')}."
    
    # Generate expected outcome based on intent
    intent = scenario['primary_intent']
    if intent == 'book_appointment':
        expected_outcome = "The bot should successfully collect service type, date, and time, then confirm the booking."
    elif intent == 'shop_info':
        expected_outcome = "The bot should provide accurate information about shop hours, location, or services."
    elif intent == 'product_inquiry':
        expected_outcome = "The bot should provide information about bikes or accessories and their availability."
    elif intent == 'maintenance_tips':
        expected_outcome = "The bot should provide helpful maintenance advice."
    elif intent == 'policy_question':
        expected_outcome = "The bot should clearly explain the relevant store policy."
    elif intent == 'recall_booking':
        expected_outcome = "The bot should help the user recall or reference their previous booking."
    else:
        expected_outcome = f"The bot should successfully handle the {intent.replace('_', ' ')} request."
    
    # User description based on behavior
    user_desc = scenario['user_behavior'].replace('_', ' ').capitalize() + " user"
    
    # Create ConversationalGolden
    golden = ConversationalGolden(
        scenario=scenario_desc,
        expected_outcome=expected_outcome,
        user_description=user_desc
    )
    
    result = {
        'test_id': test_id,
        'scenario': scenario,
        'user_goal': example.get('user_goal', ''),
        'initial_query': example.get('initial_query', ''),
        'turns': [],
        'conversation': [],
        'success': False,
        'error': None
    }
    
    try:
        # Create simulator
        simulator = ConversationSimulator(model_callback=burr_model_callback)
        
        # Simulate the conversation (max_user_simulations=5 means up to 5 user-assistant exchanges)
        test_cases = simulator.simulate(
            conversational_goldens=[golden],
            max_user_simulations=5
        )
        
        # Extract conversation from test case
        if test_cases:
            test_case = test_cases[0]
            result['turns'] = [
                {'role': turn.role, 'content': turn.content}
                for turn in test_case.turns
            ]
            result['conversation'] = result['turns']  # For backward compatibility
            result['success'] = True
        
        # Clear app cache for this test
        _app_cache.clear()
        
    except Exception as e:
        result['error'] = str(e)
    
    return result

print("✓ Function defined: run_multi_turn_test()")

✓ Function defined: run_multi_turn_test()

In [19]:
# Run tests for both conversation types sequentially
all_test_results = {}

print("\n" + "="*80)
print("RUNNING ALL TESTS")
print("="*80 + "\n")

# ==================== SINGLE-TURN ====================
print("╔" + "="*78 + "╗")
print("║" + " "*28 + "SINGLE-TURN TESTS" + " "*31 + "║")
print("╚" + "="*78 + "╝\n")

single_turn_test_examples = all_synthetic_examples['single_turn']
print(f"Starting single-turn tests: {len(single_turn_test_examples)} tests...\n")

single_turn_results = []
for idx, example in enumerate(single_turn_test_examples, 1):
    test_id = f"ST{idx:03d}"
    print(f"[{idx}/{len(single_turn_test_examples)}] Running test {test_id}: {example['scenario']['primary_intent']}...", end=" ", flush=True)
    
    result = await run_single_turn_test(example, test_id)
    single_turn_results.append(result)
    
    if result['success']:
        print(f"✓ ({result['action_taken']})")
    else:
        print(f"✗ Error: {result['error']}")

all_test_results['single_turn'] = single_turn_results

print(f"\n✓ Single-Turn Complete: {sum(1 for r in single_turn_results if r['success'])}/{len(single_turn_results)} successful\n")

# ==================== MULTI-TURN ====================
print("╔" + "="*78 + "╗")
print("║" + " "*29 + "MULTI-TURN TESTS" + " "*32 + "║")
print("╚" + "="*78 + "╝\n")

multi_turn_test_examples = all_synthetic_examples['multi_turn']
print(f"Starting multi-turn tests: {len(multi_turn_test_examples)} tests (DeepEval simulation)...\n")

multi_turn_results = []
for idx, example in enumerate(multi_turn_test_examples, 1):
    test_id = f"MT{idx:03d}"
    print(f"[{idx}/{len(multi_turn_test_examples)}] Running test {test_id}: {example['scenario']['primary_intent']}...", end=" ", flush=True)
    
    result = await run_multi_turn_test(example, test_id)
    multi_turn_results.append(result)
    
    if result['success']:
        # Count user-assistant exchanges (turns), not total messages
        num_exchanges = len([t for t in result['turns'] if t['role'] == 'user'])
        print(f"✓ ({num_exchanges} turns)")
    else:
        print(f"✗ Error: {result['error']}")

all_test_results['multi_turn'] = multi_turn_results

print(f"\n✓ Multi-Turn Complete: {sum(1 for r in multi_turn_results if r['success'])}/{len(multi_turn_results)} successful\n")

# ==================== SUMMARY ====================
print("="*80)
print("OVERALL TEST SUMMARY")
print("="*80)
total_tests = len(single_turn_results) + len(multi_turn_results)
total_success = sum(1 for r in single_turn_results if r['success']) + sum(1 for r in multi_turn_results if r['success'])
print(f"Single-Turn: {sum(1 for r in single_turn_results if r['success'])}/{len(single_turn_results)} successful")
print(f"Multi-Turn:  {sum(1 for r in multi_turn_results if r['success'])}/{len(multi_turn_results)} successful")

print(f"TOTAL:       {total_success}/{total_tests} successful")
print("="*80)

================================================================================
RUNNING ALL TESTS
================================================================================

╔==============================================================================╗
║                            SINGLE-TURN TESTS                               ║
╚==============================================================================╝

Starting single-turn tests: 8 tests...

[1/8] Running test ST001: shop_info... Chat State: {'chat_history': [{'role': 'user', 'content': "Hi there! Could you please let me know your store hours and location? I'm planning to visit soon. Thanks!", 'type': 'text'}, {'content': "Absolutely! JO's Bike Shop in Portland, OR is open 7 days a week. Our hours are Mon-Wed 9:00 AM - 6:00 PM, Thur-Fri 9:00 AM - 7:00 PM, Sat 8:00 AM - 5:00 PM, Sun 10:00 AM - 4:00 PM. We can't wait to welcome you and talk bikes! 🚲🛠️", 'type': 'text', 'role': 'assistant'}], 'appointment_data': {}, 'in_appointment_flow': False, 'awaiting_confirmation': False, 'completed_bookings': [], '__SEQUENCE_ID': 3, 'query': "Hi there! Could you please let me know your store hours and location? I'm planning to visit soon. Thanks!", '__PRIOR_STEP': 'shop_info', 'safe': True, 'mode': 'shop_info', 'response': {'content': "Absolutely! JO's Bike Shop in Portland, OR is open 7 days a week. Our hours are Mon-Wed 9:00 AM - 6:00 PM, Thur-Fri 9:00 AM - 7:00 PM, Sat 8:00 AM - 5:00 PM, Sun 10:00 AM - 4:00 PM. We can't wait to welcome you and talk bikes! 🚲🛠️", 'type': 'text', 'role': 'assistant'}}
✓ (shop_info)
[2/8] Running test ST002: shop_info... Chat State: {'chat_history': [{'role': 'user', 'content': '"Hi there! Could you please let me know your store hours and location? I\'m planning to visit this weekend and want to make sure I have the right details. Thanks!"', 'type': 'text'}, {'content': "Absolutely! JO's Bike Shop is located at 456 Pedal Lane, Portland, OR 97201. We're open this weekend on Saturday from 8:00 AM to 5:00 PM and Sunday from 10:00 AM to 4:00 PM. Can't wait to see you roll in! 🚲", 'type': 'text', 'role': 'assistant'}], 'appointment_data': {}, 'in_appointment_flow': False, 'awaiting_confirmation': False, 'completed_bookings': [], '__SEQUENCE_ID': 3, 'query': '"Hi there! Could you please let me know your store hours and location? I\'m planning to visit this weekend and want to make sure I have the right details. Thanks!"', '__PRIOR_STEP': 'shop_info', 'safe': True, 'mode': 'shop_info', 'response': {'content': "Absolutely! JO's Bike Shop is located at 456 Pedal Lane, Portland, OR 97201. We're open this weekend on Saturday from 8:00 AM to 5:00 PM and Sunday from 10:00 AM to 4:00 PM. Can't wait to see you roll in! 🚲", 'type': 'text', 'role': 'assistant'}}
✓ (shop_info)
[3/8] Running test ST003: maintenance_tips... Chat State: {'chat_history': [{'role': 'user', 'content': 'Oops, I meant to ask about bike maintenance tips. Can you help with that?', 'type': 'text'}, {'content': 'Of course! Here are some bike maintenance tips: \n\n1. Regularly clean and lubricate your chain to prevent rust and ensure smooth shifts.\n2. Check your tire pressure and tread for wear to avoid flats and maintain traction.', 'type': 'text', 'role': 'assistant'}], 'appointment_data': {}, 'in_appointment_flow': False, 'awaiting_confirmation': False, 'completed_bookings': [], '__SEQUENCE_ID': 3, 'query': 'Oops, I meant to ask about bike maintenance tips. Can you help with that?', '__PRIOR_STEP': 'maintenance_tips', 'safe': True, 'mode': 'maintenance_tips', 'response': {'content': 'Of course! Here are some bike maintenance tips: \n\n1. Regularly clean and lubricate your chain to prevent rust and ensure smooth shifts.\n2. Check your tire pressure and tread for wear to avoid flats and maintain traction.', 'type': 'text', 'role': 'assistant'}, 'modified_chat_history': [{'role': 'user', 'content': 'Please provide helpful bike maintenance tips for the following. IMPORTANT: Do not provide any pricing information - if asked about service costs, direct them to contact the shop at (503) 555-BIKE or info@josbikeshop.com. Keep your response concise: maximum 2-3 sentences: Oops, I meant to ask about bike maintenance tips. Can you help with that?', 'type': 'text'}]}
✓ (maintenance_tips)
[4/8] Running test ST004: maintenance_tips... Chat State: {'chat_history': [{'role': 'user', 'content': 'Hey there! Can you give me some tips on bike maintenance?', 'type': 'text'}, {'content': 'Of course! To keep your bike running smoothly, make sure to regularly clean and lubricate the chain, check tire pressure before each ride, and inspect the brake pads for wear. Regularly tune-ups by a professional can also help prevent bigger issues down the road.', 'type': 'text', 'role': 'assistant'}], 'appointment_data': {}, 'in_appointment_flow': False, 'awaiting_confirmation': False, 'completed_bookings': [], '__SEQUENCE_ID': 3, 'query': 'Hey there! Can you give me some tips on bike maintenance?', '__PRIOR_STEP': 'maintenance_tips', 'safe': True, 'mode': 'maintenance_tips', 'response': {'content': 'Of course! To keep your bike running smoothly, make sure to regularly clean and lubricate the chain, check tire pressure before each ride, and inspect the brake pads for wear. Regularly tune-ups by a professional can also help prevent bigger issues down the road.', 'type': 'text', 'role': 'assistant'}, 'modified_chat_history': [{'role': 'user', 'content': 'Please provide helpful bike maintenance tips for the following. IMPORTANT: Do not provide any pricing information - if asked about service costs, direct them to contact the shop at (503) 555-BIKE or info@josbikeshop.com. Keep your response concise: maximum 2-3 sentences: Hey there! Can you give me some tips on bike maintenance?', 'type': 'text'}]}
✓ (maintenance_tips)
[5/8] Running test ST005: policy_question... Chat State: {'chat_history': [{'role': 'user', 'content': "Hi there! Could you tell me a bit about your return policy for bikes? I'm considering buying one but want to know in case something doesn't work out. Thanks!", 'type': 'text'}, {'content': 'Hello! We offer a 30-day return policy for bikes, with the customer responsible for return shipping fees. If you have any concerns or questions about our policies, please feel free to contact us at (503) 555-BIKE or info@josbikeshop.com.', 'type': 'text', 'role': 'assistant'}], 'appointment_data': {}, 'in_appointment_flow': False, 'awaiting_confirmation': False, 'completed_bookings': [], '__SEQUENCE_ID': 3, 'query': "Hi there! Could you tell me a bit about your return policy for bikes? I'm considering buying one but want to know in case something doesn't work out. Thanks!", '__PRIOR_STEP': 'policy_question', 'safe': True, 'mode': 'policy_question', 'response': {'content': 'Hello! We offer a 30-day return policy for bikes, with the customer responsible for return shipping fees. If you have any concerns or questions about our policies, please feel free to contact us at (503) 555-BIKE or info@josbikeshop.com.', 'type': 'text', 'role': 'assistant'}, 'modified_chat_history': [{'role': 'user', 'content': "Please answer the customer's question about shop policies (returns, warranties, delivery). IMPORTANT: Do not provide any pricing information - if asked about costs or fees, direct them to contact the shop at (503) 555-BIKE or info@josbikeshop.com. Keep your response concise: maximum 2-3 sentences: Hi there! Could you tell me a bit about your return policy for bikes? I'm considering buying one but want to know in case something doesn't work out. Thanks!", 'type': 'text'}]}
✓ (policy_question)
[6/8] Running test ST006: policy_question... Chat State: {'chat_history': [{'role': 'user', 'content': '"Hi there! Can you tell me a bit about your warranty policy on new bikes?"', 'type': 'text'}, {'content': "Hi! Our new bikes come with a standard manufacturer's warranty. For more details or specific questions, please contact our shop at (503) 555-BIKE or info@josbikeshop.com.", 'type': 'text', 'role': 'assistant'}], 'appointment_data': {}, 'in_appointment_flow': False, 'awaiting_confirmation': False, 'completed_bookings': [], '__SEQUENCE_ID': 3, 'query': '"Hi there! Can you tell me a bit about your warranty policy on new bikes?"', '__PRIOR_STEP': 'policy_question', 'safe': True, 'mode': 'policy_question', 'response': {'content': "Hi! Our new bikes come with a standard manufacturer's warranty. For more details or specific questions, please contact our shop at (503) 555-BIKE or info@josbikeshop.com.", 'type': 'text', 'role': 'assistant'}, 'modified_chat_history': [{'role': 'user', 'content': 'Please answer the customer\'s question about shop policies (returns, warranties, delivery). IMPORTANT: Do not provide any pricing information - if asked about costs or fees, direct them to contact the shop at (503) 555-BIKE or info@josbikeshop.com. Keep your response concise: maximum 2-3 sentences: "Hi there! Can you tell me a bit about your warranty policy on new bikes?"', 'type': 'text'}]}
✓ (policy_question)
[7/8] Running test ST007: what_can_you_do... Chat State: {'chat_history': [{'role': 'user', 'content': '"Hi there! Can you tell me everything you can help me with at your bike shop?"', 'type': 'text'}, {'content': "I'm here to help you with JO's Bike Shop! I can assist you with:\n\n• **Shop Information** - Opening hours, location, and contact details\n\n• **Product Inquiries** - Available bikes, accessories, and product availability\n\n• **Service Appointments** - Booking bike service and repairs\n\n• **Maintenance Tips** - Advice on keeping your bike in top condition\n\n• **Shop Policies** - Questions about returns, warranties, and delivery\n\nHow can I help you today?", 'type': 'text', 'role': 'assistant'}], 'appointment_data': {}, 'in_appointment_flow': False, 'awaiting_confirmation': False, 'completed_bookings': [], '__SEQUENCE_ID': 3, 'query': '"Hi there! Can you tell me everything you can help me with at your bike shop?"', '__PRIOR_STEP': 'what_can_you_do', 'safe': True, 'mode': 'what_can_you_do', 'response': {'content': "I'm here to help you with JO's Bike Shop! I can assist you with:\n\n• **Shop Information** - Opening hours, location, and contact details\n\n• **Product Inquiries** - Available bikes, accessories, and product availability\n\n• **Service Appointments** - Booking bike service and repairs\n\n• **Maintenance Tips** - Advice on keeping your bike in top condition\n\n• **Shop Policies** - Questions about returns, warranties, and delivery\n\nHow can I help you today?", 'type': 'text', 'role': 'assistant'}}
✓ (what_can_you_do)
[8/8] Running test ST008: what_can_you_do... Chat State: {'chat_history': [{'role': 'user', 'content': '"Hi there! Could you tell me all the different things you can help me with at your bike shop?"', 'type': 'text'}, {'content': "I'm here to help you with JO's Bike Shop! I can assist you with:\n\n• **Shop Information** - Opening hours, location, and contact details\n\n• **Product Inquiries** - Available bikes, accessories, and product availability\n\n• **Service Appointments** - Booking bike service and repairs\n\n• **Maintenance Tips** - Advice on keeping your bike in top condition\n\n• **Shop Policies** - Questions about returns, warranties, and delivery\n\nHow can I help you today?", 'type': 'text', 'role': 'assistant'}], 'appointment_data': {}, 'in_appointment_flow': False, 'awaiting_confirmation': False, 'completed_bookings': [], '__SEQUENCE_ID': 3, 'query': '"Hi there! Could you tell me all the different things you can help me with at your bike shop?"', '__PRIOR_STEP': 'what_can_you_do', 'safe': True, 'mode': 'what_can_you_do', 'response': {'content': "I'm here to help you with JO's Bike Shop! I can assist you with:\n\n• **Shop Information** - Opening hours, location, and contact details\n\n• **Product Inquiries** - Available bikes, accessories, and product availability\n\n• **Service Appointments** - Booking bike service and repairs\n\n• **Maintenance Tips** - Advice on keeping your bike in top condition\n\n• **Shop Policies** - Questions about returns, warranties, and delivery\n\nHow can I help you today?", 'type': 'text', 'role': 'assistant'}}
✓ (what_can_you_do)

✓ Single-Turn Complete: 8/8 successful

╔==============================================================================╗
║                             MULTI-TURN TESTS                                ║
╚==============================================================================╝

Starting multi-turn tests: 16 tests (DeepEval simulation)...

[1/16] Running test MT001: product_inquiry...

Overriding of current TracerProvider is not allowed

Output()

✓ (3 turns)
[2/16] Running test MT002: book_appointment...

Output()

✓ (5 turns)
[3/16] Running test MT003: policy_question...

Output()

✓ (2 turns)
[4/16] Running test MT004: recall_booking...

Output()

✓ (5 turns)
[5/16] Running test MT005: what_can_you_do...

Output()

✓ (1 turns)
[6/16] Running test MT006: book_appointment...

Output()

✓ (5 turns)
[7/16] Running test MT007: maintenance_tips...

Output()

✓ (1 turns)
[8/16] Running test MT008: book_appointment...

Output()

✓ (5 turns)
[9/16] Running test MT009: product_inquiry...

Output()

✓ (5 turns)
[10/16] Running test MT010: recall_booking...

Output()

✓ (5 turns)
[11/16] Running test MT011: book_appointment...

Output()

✓ (5 turns)
[12/16] Running test MT012: shop_info...

Output()

✓ (2 turns)
[13/16] Running test MT013: book_appointment...

Output()

✓ (5 turns)
[14/16] Running test MT014: product_inquiry...

Output()

✓ (5 turns)
[15/16] Running test MT015: maintenance_tips...

Output()

✓ (1 turns)
[16/16] Running test MT016: book_appointment...

Output()

✓ (5 turns)

✓ Multi-Turn Complete: 16/16 successful

================================================================================
OVERALL TEST SUMMARY
================================================================================
Single-Turn: 8/8 successful
Multi-Turn:  16/16 successful
TOTAL:       24/24 successful
================================================================================

### Running All Tests

This cell executes both test types sequentially:
1. **Single-Turn** tests run each query against the chatbot and capture the response
2. **Multi-Turn** tests use DeepEval's conversation simulator to create realistic dialogs

Progress is displayed in real-time so you can monitor the testing.

In [20]:
# Display sample results from both conversation types
print("\n" + "="*80)
print("SAMPLE TEST RESULTS")
print("="*80)

print("\n--- SINGLE-TURN SAMPLES ---\n")
for i, result in enumerate(all_test_results['single_turn'], 1):
    print(f"Test {result['test_id']}")
    print(f"Scenario: {result['scenario']['tuple']}")
    print(f"User Query: \"{result['user_query']}\"")
    print(f"Bot Response: {result['bot_response']}")
    print(f"Mode: {result['state_snapshot']['mode']}")
    print("-"*80 + "\n")

print("--- MULTI-TURN SAMPLES ---\n")
for i, result in enumerate(all_test_results['multi_turn'], 1):
    print(f"Test {result['test_id']}")
    print(f"Scenario: {result['scenario']['tuple']}")
    print(f"Goal: {result['user_goal']}")
    
    # Group messages into user-assistant exchanges (turns)
    # Each turn = 1 user message + 1 assistant response
    turns = result['turns']
    num_exchanges = len([t for t in turns if t['role'] == 'user'])
    print(f"Conversation ({num_exchanges} turns):\n")
    
    # Display conversation showing each user-assistant exchange as one "turn"
    exchange_num = 0
    i = 0
    while i < len(turns):
        if turns[i]['role'] == 'user':
            exchange_num += 1
            user_content = turns[i]['content']
            print(f"  Turn {exchange_num}:")
            print(f"    User: {user_content}")
            
            # Look for assistant response
            if i + 1 < len(turns) and turns[i + 1]['role'] == 'assistant':
                assistant_content = turns[i + 1]['content']
                print(f"    Assistant: {assistant_content}")
                i += 2
            else:
                print(f"    Assistant: [no response]")
                i += 1
        else:
            i += 1
    
    print("-"*80 + "\n")

================================================================================
SAMPLE TEST RESULTS
================================================================================

--- SINGLE-TURN SAMPLES ---

Test ST001
Scenario: (shop_info, complete_upfront, single_turn, cooperative)
User Query: "Hi there! Could you please let me know your store hours and location? I'm planning to visit soon. Thanks!"
Bot Response: Absolutely! JO's Bike Shop in Portland, OR is open 7 days a week. Our hours are Mon-Wed 9:00 AM - 6:00 PM, Thur-Fri 9:00 AM - 7:00 PM, Sat 8:00 AM - 5:00 PM, Sun 10:00 AM - 4:00 PM. We can't wait to welcome you and talk bikes! 🚲🛠️
Mode: shop_info
--------------------------------------------------------------------------------

Test ST002
Scenario: (shop_info, complete_upfront, single_turn, cooperative)
User Query: ""Hi there! Could you please let me know your store hours and location? I'm planning to visit this weekend and want to make sure I have the right details. Thanks!""
Bot Response: Absolutely! JO's Bike Shop is located at 456 Pedal Lane, Portland, OR 97201. We're open this weekend on Saturday from 8:00 AM to 5:00 PM and Sunday from 10:00 AM to 4:00 PM. Can't wait to see you roll in! 🚲
Mode: shop_info
--------------------------------------------------------------------------------

Test ST003
Scenario: (maintenance_tips, no_info, single_turn, corrective)
User Query: "Oops, I meant to ask about bike maintenance tips. Can you help with that?"
Bot Response: Of course! Here are some bike maintenance tips:

1. Regularly clean and lubricate your chain to prevent rust and ensure smooth shifts.
2. Check your tire pressure and tread for wear to avoid flats and maintain traction.
Mode: maintenance_tips
--------------------------------------------------------------------------------

Test ST004
Scenario: (maintenance_tips, no_info, single_turn, corrective)
User Query: "Hey there! Can you give me some tips on bike maintenance?"
Bot Response: Of course! To keep your bike running smoothly, make sure to regularly clean and lubricate the chain, check tire pressure before each ride, and inspect the brake pads for wear. Regularly tune-ups by a professional can also help prevent bigger issues down the road.
Mode: maintenance_tips
--------------------------------------------------------------------------------

Test ST005
Scenario: (policy_question, partial_info, single_turn, cooperative)
User Query: "Hi there! Could you tell me a bit about your return policy for bikes? I'm considering buying one but want to know in case something doesn't work out. Thanks!"
Bot Response: Hello! We offer a 30-day return policy for bikes, with the customer responsible for return shipping fees. If you have any concerns or questions about our policies, please feel free to contact us at (503) 555-BIKE or info@josbikeshop.com.
Mode: policy_question
--------------------------------------------------------------------------------

Test ST006
Scenario: (policy_question, partial_info, single_turn, cooperative)
User Query: ""Hi there! Can you tell me a bit about your warranty policy on new bikes?""
Bot Response: Hi! Our new bikes come with a standard manufacturer's warranty. For more details or specific questions, please contact our shop at (503) 555-BIKE or info@josbikeshop.com.
Mode: policy_question
--------------------------------------------------------------------------------

Test ST007
Scenario: (what_can_you_do, complete_upfront, single_turn, cooperative)
User Query: ""Hi there! Can you tell me everything you can help me with at your bike shop?""
Bot Response: I'm here to help you with JO's Bike Shop! I can assist you with:

• **Shop Information** - Opening hours, location, and contact details

• **Product Inquiries** - Available bikes, accessories, and product availability

• **Service Appointments** - Booking bike service and repairs

• **Maintenance Tips** - Advice on keeping your bike in top condition

• **Shop Policies** - Questions about returns, warranties, and delivery

How can I help you today?
Mode: what_can_you_do
--------------------------------------------------------------------------------

Test ST008
Scenario: (what_can_you_do, complete_upfront, single_turn, cooperative)
User Query: ""Hi there! Could you tell me all the different things you can help me with at your bike shop?""
Bot Response: I'm here to help you with JO's Bike Shop! I can assist you with:

• **Shop Information** - Opening hours, location, and contact details

• **Product Inquiries** - Available bikes, accessories, and product availability

• **Service Appointments** - Booking bike service and repairs

• **Maintenance Tips** - Advice on keeping your bike in top condition

• **Shop Policies** - Questions about returns, warranties, and delivery

How can I help you today?
Mode: what_can_you_do
--------------------------------------------------------------------------------

--- MULTI-TURN SAMPLES ---

Test MT001
Scenario: (product_inquiry, partial_info, multi_turn_linear, conversational)
Goal: Learn about specific bikes or accessories and their availability
Conversation (3 turns):

  Turn 1:
    User: Hi there! I’m interested in learning more about one of your products and had a few questions. Could you help me out?
    Assistant: Of course! I'd be happy to help. Please let me know which product you're interested in and what questions you have.
  Turn 2:
    User: Thanks! I’m looking at your wireless earbuds—can you tell me about their battery life and if they’re sweat-resistant?
    Assistant: Our wireless earbuds have a battery life of up to 8 hours on a single charge and are sweat-resistant, making them perfect for workouts or outdoor activities. Feel free to reach out to us if you have any more questions or would like more information.
  Turn 3:
    User: That sounds great! Do they come with a charging case, and how long does it take to fully charge them?
    Assistant: Yes, our wireless earbuds come with a charging case for convenient on-the-go charging. It takes approximately 1-2 hours to fully charge the earbuds in the case. Feel free to contact us if you have any more questions.
--------------------------------------------------------------------------------

Test MT002
Scenario: (book_appointment, minimal_info, multi_turn_complex, cooperative)
Goal: Successfully book a service appointment by providing service type, date, and time
Conversation (5 turns):

  Turn 1:
    User: Hello! I’d like to book an appointment, please. Could you help me with the available times?
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 2:
    User: I’d like to schedule a tune-up, please. What days and times are available?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 3:
    User: Next Friday would be perfect for me—do you have any openings then?
    Assistant: Great! I have you down for a tune-up. What time would you prefer? We have morning (8am-12pm) and afternoon (1pm-5pm) slots available.
  Turn 4:
    User: Afternoon would be best—can I book a 2pm slot, please?
    Assistant: Perfect! Let me confirm your appointment:

• Service: tune-up
• Date: next Friday
• Time: 2pm

Does this look correct? I can book this for you now!
  Turn 5:
    User: Yes, that’s perfect—please go ahead and book it. Thank you!
    Assistant: Excellent! Your appointment has been booked. We'll see you then! Is there anything else I can help you with?
--------------------------------------------------------------------------------

Test MT003
Scenario: (policy_question, complete_upfront, multi_turn_linear, distracted)
Goal: Understand store policies regarding returns, warranties, or delivery
Conversation (2 turns):

  Turn 1:
    User: Hey, sorry if I seem a bit all over the place, but I had a quick question about a policy and could use some help understanding it.
    Assistant: Absolutely, happy to help! For any questions regarding our shop policies on returns, warranties, or delivery, please feel free to contact us directly at (503) 555-BIKE or info@josbikeshop.com. We're here to assist with any inquiries you may have.
  Turn 2:
    User: Oh, thanks! Um, actually, I was wondering—what's your return policy if I accidentally order the wrong part?
    Assistant: Our return policy allows for exchanges or refunds on items in new, unused condition within 30 days of purchase. For further details or if you have any specific questions, please reach out to us at (503) 555-BIKE or info@josbikeshop.com.
--------------------------------------------------------------------------------

Test MT004
Scenario: (recall_booking, partial_info, multi_turn_complex, cooperative)
Goal: Successfully recall or reference a previously made booking
Conversation (5 turns):

  Turn 1:
    User: Hi there! I’d like to check on a booking I made earlier—could you help me recall the details?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 2:
    User: Actually, I made the booking a few days ago—could you check if you have it on file under my name?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 3:
    User: Could you check using my name or email address to see if the booking comes up in your system?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 4:
    User: Yes, let's go ahead and book an appointment then. What times are available?
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 5:
    User: I’d like to book a tune-up, please—could you let me know what times are available for that?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
--------------------------------------------------------------------------------

Test MT005
Scenario: (what_can_you_do, no_info, mixed_intent, conversational)
Goal: Complete a what_can_you_do interaction successfully
Conversation (1 turns):

  Turn 1:
    User: Hi there! I’m curious—what kinds of things can you help me with?
    Assistant: I'm here to help you with JO's Bike Shop! I can assist you with:

• **Shop Information** - Opening hours, location, and contact details

• **Product Inquiries** - Available bikes, accessories, and product availability

• **Service Appointments** - Booking bike service and repairs

• **Maintenance Tips** - Advice on keeping your bike in top condition

• **Shop Policies** - Questions about returns, warranties, and delivery

How can I help you today?
--------------------------------------------------------------------------------

Test MT006
Scenario: (book_appointment, complete_upfront, multi_turn_linear, cooperative)
Goal: Successfully book a service appointment by providing service type, date, and time
Conversation (5 turns):

  Turn 1:
    User: Hi there! I’d like to book an appointment and was hoping you could help me with the process.
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 2:
    User: I’d like to schedule a tune-up, please. What dates and times are available?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 3:
    User: Next Friday would be perfect for me—do you have any openings then?
    Assistant: Great! I have you down for a tune-up. What time would you prefer? We have morning (8am-12pm) and afternoon (1pm-5pm) slots available.
  Turn 4:
    User: Afternoon would be best—can I book a slot around 2pm?
    Assistant: Perfect! Let me confirm your appointment:

• Service: tune-up
• Date: next Friday
• Time: afternoon

Does this look correct? I can book this for you now!
  Turn 5:
    User: Yes, that looks great—please go ahead and book it for me. Thank you!
    Assistant: Excellent! Your appointment has been booked. We'll see you then! Is there anything else I can help you with?
--------------------------------------------------------------------------------

Test MT007
Scenario: (maintenance_tips, partial_info, multi_turn_linear, cooperative)
Goal: Get practical advice on bike maintenance or care
Conversation (1 turns):

  Turn 1:
    User: Hi there! I’m looking for some helpful maintenance tips—could you share some advice to get me started?
    Assistant: Of course! Here are some basic bike maintenance tips:
1. Keep your tires properly inflated to prevent punctures and improve ride quality.
2. Regularly clean and lubricate your chain to ensure smooth shifting and prolong its lifespan.
3. Check your brakes regularly for wear and adjust as needed to maintain proper stopping power.
--------------------------------------------------------------------------------

Test MT008
Scenario: (book_appointment, no_info, multi_turn_complex, distracted)
Goal: Successfully book a service appointment by providing service type, date, and time
Conversation (5 turns):

  Turn 1:
    User: Hey, sorry, I keep getting sidetracked, but I need to book an appointment—can you help me with that?
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 2:
    User: Oh right, sorry—um, I think I need a tune-up for my bike. What times do you have available?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 3:
    User: Oh, um, let me think—maybe next Wednesday? Or wait, is that too soon?
    Assistant: Great! I have you down for a tune-up. What time would you prefer? We have morning (8am-12pm) and afternoon (1pm-5pm) slots available.
  Turn 4:
    User: Oh, sorry, I keep losing track—afternoon would be better for me, I think. Is 2pm open?
    Assistant: Perfect! Let me confirm your appointment:

• Service: tune-up
• Date: next Wednesday
• Time: afternoon

Does this look correct? I can book this for you now!
  Turn 5:
    User: Yes, that looks good—please go ahead and book it for me. Thanks for your patience!
    Assistant: Excellent! Your appointment has been booked. We'll see you then! Is there anything else I can help you with?
--------------------------------------------------------------------------------

Test MT009
Scenario: (product_inquiry, minimal_info, mixed_intent, corrective)
Goal: Learn about specific bikes or accessories and their availability
Conversation (5 turns):

  Turn 1:
    User: Hello, I have a few questions about one of your products and want to make sure I have the correct information. Could you help me with some details?
    Assistant: Of course! I'd be happy to help. Please let me know which product you are inquiring about, and I will provide you with the necessary information.
  Turn 2:
    User: I'm asking about the Model X wireless headphones—can you confirm if they support Bluetooth 5.2 and active noise cancellation?
    Assistant: Yes, the Model X wireless headphones support Bluetooth 5.2 technology and feature active noise cancellation for an enhanced listening experience.
  Turn 3:
    User: Thank you for confirming. Could you also clarify if the Model X headphones are compatible with both iOS and Android devices?
    Assistant: Yes, the Model X wireless headphones are compatible with both iOS and Android devices, allowing you to easily connect and enjoy your music or audio content across different platforms.
  Turn 4:
    User: Great, thanks for clarifying. One more thing—can you confirm the battery life on a single charge and whether the headphones support fast charging?
    Assistant: The Model X wireless headphones offer a battery life of up to 20 hours on a single charge and support fast charging for quick recharging when needed.
  Turn 5:
    User: Thank you for confirming. Lastly, could you specify if the Model X headphones come with a warranty and what it covers?
    Assistant: The Model X wireless headphones come with a one-year manufacturer's warranty that covers any defects in materials or workmanship. For more information on our shop policies including returns and delivery, please contact us at (503) 555-BIKE or info@josbikeshop.com.
--------------------------------------------------------------------------------

Test MT010
Scenario: (recall_booking, minimal_info, multi_turn_linear, corrective)
Goal: Successfully recall or reference a previously made booking
Conversation (5 turns):

  Turn 1:
    User: Hi, I’d like to check the details of a booking I made earlier. Can you help me recall it?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 2:
    User: Actually, I made a booking yesterday—could you check under my account or by my email address?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 3:
    User: I’m sure I made a booking—can you please double-check using my account details or email?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 4:
    User: Can you please check again using my email address? I definitely made a booking yesterday.
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 5:
    User: I’m certain I booked yesterday—can you escalate this or check with support using my email address?
    Assistant: I'm sorry for the inconvenience. For support regarding your booking, please reach out to support directly at info@josbikeshop.com, or give us a call at (503) 555-BIKE. If you need help with anything else related to our shop or services, feel free to ask!
--------------------------------------------------------------------------------

Test MT011
Scenario: (book_appointment, minimal_info, multi_turn_linear, canceling)
Goal: Successfully book a service appointment by providing service type, date, and time
Conversation (5 turns):

  Turn 1:
    User: Hi there, I’d like to book an appointment, but I’m a bit unsure about my schedule. Could you help me find a time that’s easy to reschedule if needed?
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 2:
    User: I’m looking to book a tune-up, but I might need to change the time later—what’s your cancellation policy?
    Assistant: No problem! I've canceled the appointment booking. Is there anything else I can help you with?
  Turn 3:
    User: Actually, I still want to book a tune-up—could you suggest a time that’s easy to move if I need to reschedule?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 4:
    User: Could you recommend a date that’s usually less busy, in case I need to change it last minute?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 5:
    User: Is there a day next week that tends to have more open slots or is easier to reschedule?
    Assistant: Great! I have you down for a tune-up. What time would you prefer? We have morning (8am-12pm) and afternoon (1pm-5pm) slots available.
--------------------------------------------------------------------------------

Test MT012
Scenario: (shop_info, no_info, mixed_intent, distracted)
Goal: Get specific information about shop hours, location, or services
Conversation (2 turns):

  Turn 1:
    User: Hey, I was hoping you could help me find some info about shopping, but I might get a bit sidetracked—can you keep things simple for me?
    Assistant: I'm here to help you with JO's Bike Shop! I can assist you with:

• **Shop Information** - Opening hours, location, and contact details

• **Product Inquiries** - Available bikes, accessories, and product availability

• **Service Appointments** - Booking bike service and repairs


In [21]:
# Save test results for both conversation types
print("\n" + "="*80)
print("SAVING RESULTS")
print("="*80 + "\n")

for conv_type in ['single_turn', 'multi_turn']:
    results = all_test_results[conv_type]
    
    output_data = {
        'metadata': {
            'conversation_type': conv_type,
            'description': f'{conv_type.replace("_", "-").title()} conversation tests',
            'timestamp': pd.Timestamp.now().isoformat(),
            'total_tests': len(results),
            'successful_tests': sum(1 for r in results if r['success'])
        },
        'results': results
    }
    
    output_filename = f'{conv_type}_results.json'
    with open(output_filename, 'w') as f:
        json.dump(output_data, f, indent=2)
    
    print(f"✓ {conv_type.replace('_', '-').title()}: Saved to {output_filename}")
    print(f"  Total tests: {len(results)}")
    print(f"  Successful: {sum(1 for r in results if r['success'])}")
    print(f"  Failed: {sum(1 for r in results if not r['success'])}\n")

print("="*80)
print("✓ All results saved successfully")
print("="*80)

================================================================================
SAVING RESULTS
================================================================================

✓ Single-Turn: Saved to single_turn_results.json
  Total tests: 8
  Successful: 8
  Failed: 0

✓ Multi-Turn: Saved to multi_turn_results.json
  Total tests: 16
  Successful: 16
  Failed: 0

================================================================================
✓ All results saved successfully
================================================================================

### Saving Results

We save two types of files:
- **JSON files** (`single_turn_results.json`, `multi_turn_results.json`): Complete raw data with full conversations
- **CSV files** (`single_turn_analysis.csv`, `multi_turn_analysis.csv`): Structured format for manual open coding analysis

In [22]:
# Create analysis CSV for open coding (both conversation types)
print("\n" + "="*80)
print("CREATING ANALYSIS CSVs")
print("="*80 + "\n")

for conv_type in ['single_turn', 'multi_turn']:
    results = all_test_results[conv_type]
    analysis_rows = []
    
    for result in results:
        scenario = result['scenario']
        
        # Single-turn has user_query, multi-turn has initial_query and user_goal
        if conv_type == 'single_turn':
            user_input = result['user_query']
            bot_preview = result['bot_response'][:200] if result['bot_response'] else ''
        else:  # multi_turn
            user_input = result.get('initial_query', '')
            # For multi-turn, count user-assistant exchanges (turns), not total messages
            turns_list = result.get('turns', [])
            num_exchanges = len([t for t in turns_list if t['role'] == 'user'])
            bot_preview = f"Goal: {result.get('user_goal', '')} | Turns: {num_exchanges}"
        
        row = {
            'Trace_ID': result['test_id'],
            'Conversation_Type': conv_type,
            'Scenario_Tuple': scenario['tuple'],
            'Primary_Intent': scenario['primary_intent'],
            'Completeness': scenario['completeness'],
            'Interaction_Pattern': scenario['interaction_pattern'],
            'User_Behavior': scenario['user_behavior'],
            'User_Query': user_input,
            'Bot_Response_Preview': bot_preview,
            'Action_Taken': result.get('action_taken', ''),
            'Mode_Detected': result['state_snapshot']['mode'] if result.get('state_snapshot') else '',
            'Success': 1 if result['success'] else 0,
            'Error': result['error'] or '',
            'Open_Code_Notes': '',  # For manual analysis
            'Overall_Success': '',  # 0=failed, 1=partial, 2=success (to fill manually)
        }
        analysis_rows.append(row)
    
    analysis_df = pd.DataFrame(analysis_rows)
    csv_filename = f'{conv_type}_analysis.csv'
    analysis_df.to_csv(csv_filename, index=False)
    
    print(f"✓ {conv_type.replace('_', '-').title()}: Created {csv_filename} ({len(analysis_rows)} rows)\n")

print("="*80)

print("✓ All analysis CSVs created")
print("="*80)

================================================================================
CREATING ANALYSIS CSVs
================================================================================

✓ Single-Turn: Created single_turn_analysis.csv (8 rows)

✓ Multi-Turn: Created multi_turn_analysis.csv (16 rows)

================================================================================
✓ All analysis CSVs created
================================================================================

### Testing Summary

**Completed:**
- ✅ Generated synthetic examples for single-turn and multi-turn conversations
- ✅ Ran chatbot against all generated queries
- ✅ Captured bot responses and state information
- ✅ Saved results to JSON files (detailed)
- ✅ Created CSV files for open coding

**Files Created:**
- `single_turn_results.json` - Complete single-turn test results
- `multi_turn_results.json` - Complete multi-turn test results
- `single_turn_analysis.csv` - Single-turn analysis spreadsheet
- `multi_turn_analysis.csv` - Multi-turn analysis spreadsheet

**Next Steps:**
1. Review results in Burr UI: `burr` (look for traces starting with `ST` or `MT`)
2. Perform open coding: Fill in `Open_Code_Notes` column in the CSV files
3. Analyze patterns across both conversation types