# Error Analysis for JO's Bike Shop Multi-Turn Chatbot

This notebook implements the error analysis methodology described in `error_analysis_plan.md` using open coding and axial coding techniques.

## Part 1: Define Dimensions & Generate Initial Queries

### 1.1 Identified Dimensions

**Dimension 1: Primary Intent** (conversation_mode)
- `shop_info`, `product_inquiry`, `book_appointment`, `maintenance_tips`, `policy_question`, `recall_booking`, `what_can_you_do`

**Dimension 2: Information Completeness** (booking_completeness)
- `complete_upfront`, `partial_info`, `minimal_info`, `no_info`

**Dimension 3: Conversation Complexity** (interaction_pattern)
- `single_turn`, `multi_turn_linear`, `multi_turn_complex`, `mixed_intent`

**Dimension 4: User Behavior Pattern** (user_behavior)
- `cooperative`, `conversational`, `corrective`, `distracted`, `canceling`

### 1.2 Generate Unique Combinations (Tuples)

Using an LLM to generate diverse test scenario combinations.

In [1]:
# Fix OpenTelemetry TracerProvider conflict
import os

# Disable OpenTelemetry to prevent TracerProvider override conflicts
os.environ["OTEL_SDK_DISABLED"] = "true"
os.environ["OTEL_PYTHON_CONFIGURATOR"] = "default"

print("✓ OpenTelemetry disabled to prevent tracing conflicts")

✓ OpenTelemetry disabled to prevent tracing conflicts

In [2]:
# Install ipywidgets for Jupyter rich display support
! pip install ipywidgets -q

In [3]:
import os
from openai import OpenAI
import nest_asyncio
nest_asyncio.apply()

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

### Setup & Dependencies

We'll use OpenAI's GPT-4o to generate test scenarios and queries. The `nest_asyncio` library allows us to run async code in Jupyter notebooks.

In [4]:
# Prompt for generating test scenario combinations
combination_prompt = """You are helping create test scenarios for a bike shop chatbot that handles multi-turn conversations. 

Generate 20 unique test scenario combinations using these dimensions:

1. Primary Intent: shop_info, product_inquiry, book_appointment, maintenance_tips, policy_question, recall_booking, what_can_you_do
2. Information Completeness: complete_upfront, partial_info, minimal_info, no_info
3. Interaction Pattern: single_turn, multi_turn_linear, multi_turn_complex, mixed_intent
4. User Behavior: cooperative, conversational, corrective, distracted, canceling

For each combination, output as a tuple: (primary_intent, completeness, interaction_pattern, user_behavior)

Ensure diverse coverage:
- Include at least 5 book_appointment scenarios (this is the main multi-turn feature)
- Include at least 2 recall_booking scenarios
- Include at least 3 scenarios with corrective or distracted behavior
- Vary the interaction patterns to test different conversation flows

Output format: One tuple per line, e.g.:
(book_appointment, partial_info, multi_turn_linear, cooperative)

Return ONLY the tuples, one per line, no additional text or explanation."""

# Call OpenAI API to generate combinations
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "system", "content": "You are a helpful assistant that generates test scenarios for chatbot evaluation."},
        {"role": "user", "content": combination_prompt}
    ],
    temperature=0.8,  # Higher temperature for more diverse combinations
)

# Extract and display the generated combinations
generated_combinations = response.choices[0].message.content
print(generated_combinations)

(shop_info, complete_upfront, single_turn, cooperative)
(product_inquiry, partial_info, multi_turn_linear, conversational)
(book_appointment, minimal_info, multi_turn_complex, cooperative)
(maintenance_tips, no_info, multi_turn_complex, distracted)
(policy_question, complete_upfront, multi_turn_linear, cooperative)
(recall_booking, partial_info, multi_turn_linear, corrective)
(book_appointment, complete_upfront, multi_turn_linear, cooperative)
(what_can_you_do, no_info, single_turn, conversational)
(product_inquiry, partial_info, mixed_intent, distracted)
(maintenance_tips, complete_upfront, single_turn, cooperative)
(book_appointment, partial_info, mixed_intent, distracted)
(policy_question, minimal_info, multi_turn_complex, cooperative)
(recall_booking, no_info, multi_turn_complex, cooperative)
(book_appointment, no_info, multi_turn_linear, cooperative)
(what_can_you_do, partial_info, mixed_intent, corrective)
(shop_info, minimal_info, multi_turn_linear, cooperative)
(book_appointment, partial_info, multi_turn_complex, canceling)
(product_inquiry, complete_upfront, multi_turn_complex, cooperative)
(recall_booking, minimal_info, mixed_intent, conversational)
(book_appointment, complete_upfront, multi_turn_complex, cooperative)

In [5]:
# Parse the combinations into a structured list
import re

# Extract tuples from the text
tuple_pattern = r'\([^)]+\)'
tuples_raw = re.findall(tuple_pattern, generated_combinations)

# Parse each tuple
test_scenarios = []
for tuple_str in tuples_raw:
    # Remove parentheses and split by comma
    parts = tuple_str.strip('()').split(', ')
    if len(parts) == 4:
        test_scenarios.append({
            'primary_intent': parts[0],
            'completeness': parts[1],
            'interaction_pattern': parts[2],
            'user_behavior': parts[3],
            'tuple': tuple_str
        })

print(f"Generated {len(test_scenarios)} test scenarios:\n")
for i, scenario in enumerate(test_scenarios, 1):
    print(f"{i}. {scenario['tuple']}")

Generated 20 test scenarios:

1. (shop_info, complete_upfront, single_turn, cooperative)
2. (product_inquiry, partial_info, multi_turn_linear, conversational)
3. (book_appointment, minimal_info, multi_turn_complex, cooperative)
4. (maintenance_tips, no_info, multi_turn_complex, distracted)
5. (policy_question, complete_upfront, multi_turn_linear, cooperative)
6. (recall_booking, partial_info, multi_turn_linear, corrective)
7. (book_appointment, complete_upfront, multi_turn_linear, cooperative)
8. (what_can_you_do, no_info, single_turn, conversational)
9. (product_inquiry, partial_info, mixed_intent, distracted)
10. (maintenance_tips, complete_upfront, single_turn, cooperative)
11. (book_appointment, partial_info, mixed_intent, distracted)
12. (policy_question, minimal_info, multi_turn_complex, cooperative)
13. (recall_booking, no_info, multi_turn_complex, cooperative)
14. (book_appointment, no_info, multi_turn_linear, cooperative)
15. (what_can_you_do, partial_info, mixed_intent, corrective)
16. (shop_info, minimal_info, multi_turn_linear, cooperative)
17. (book_appointment, partial_info, multi_turn_complex, canceling)
18. (product_inquiry, complete_upfront, multi_turn_complex, cooperative)
19. (recall_booking, minimal_info, mixed_intent, conversational)
20. (book_appointment, complete_upfront, multi_turn_complex, cooperative)

In [6]:
# Save the generated combinations to a file for future reference
import json

output_file = 'test_scenario_combinations.json'

with open(output_file, 'w') as f:
    json.dump(test_scenarios, f, indent=2)

print(f"\n✓ Saved {len(test_scenarios)} test scenarios to {output_file}")

✓ Saved 20 test scenarios to test_scenario_combinations.json

#### Analyze Scenario Distribution

Let's examine how our generated scenarios are distributed across the different dimensions. This helps ensure we have good coverage for testing.

In [7]:
# Analyze the distribution of scenarios
import pandas as pd

df = pd.DataFrame(test_scenarios)

print("Distribution by Primary Intent:")
print(df['primary_intent'].value_counts())
print("\nDistribution by Information Completeness:")
print(df['completeness'].value_counts())
print("\nDistribution by Interaction Pattern:")
print(df['interaction_pattern'].value_counts())
print("\nDistribution by User Behavior:")
print(df['user_behavior'].value_counts())

Distribution by Primary Intent:
primary_intent
book_appointment    6
product_inquiry     3
recall_booking      3
shop_info           2
maintenance_tips    2
policy_question     2
what_can_you_do     2
Name: count, dtype: int64

Distribution by Information Completeness:
completeness
complete_upfront    6
partial_info        6
minimal_info        4
no_info             4
Name: count, dtype: int64

Distribution by Interaction Pattern:
interaction_pattern
multi_turn_complex    7
multi_turn_linear     6
mixed_intent          4
single_turn           3
Name: count, dtype: int64

Distribution by User Behavior:
user_behavior
cooperative       11
conversational     3
distracted         3
corrective         2
canceling          1
Name: count, dtype: int64

In [8]:
df.drop(columns=['tuple'])

      primary_intent      completeness interaction_pattern   user_behavior
0          shop_info  complete_upfront         single_turn     cooperative
1    product_inquiry      partial_info   multi_turn_linear  conversational
2   book_appointment      minimal_info  multi_turn_complex     cooperative
3   maintenance_tips           no_info  multi_turn_complex      distracted
4    policy_question  complete_upfront   multi_turn_linear     cooperative
5     recall_booking      partial_info   multi_turn_linear      corrective
6   book_appointment  complete_upfront   multi_turn_linear     cooperative
7    what_can_you_do           no_info         single_turn  conversational
8    product_inquiry      partial_info        mixed_intent      distracted
9   maintenance_tips  complete_upfront         single_turn     cooperative
10  book_appointment      partial_info        mixed_intent      distracted
11   policy_question      minimal_info  multi_turn_complex     cooperative
12    recall_booking           no_info  multi_turn_complex     cooperative
13  book_appointment           no_info   multi_turn_linear     cooperative
14   what_can_you_do      partial_info        mixed_intent      corrective
15         shop_info      minimal_info   multi_turn_linear     cooperative
16  book_appointment      partial_info  multi_turn_complex       canceling
17   product_inquiry  complete_upfront  multi_turn_complex     cooperative
18    recall_booking      minimal_info        mixed_intent  conversational
19  book_appointment  complete_upfront  multi_turn_complex     cooperative

In [9]:
df[df['interaction_pattern'] == 'single_turn']

,primary_intent,completeness,interaction_pattern,user_behavior,tuple
0,shop_info,complete_upfront,single_turn,cooperative,"(shop_info, complete_upfront, single_turn, coo..."
7,what_can_you_do,no_info,single_turn,conversational,"(what_can_you_do, no_info, single_turn, conver..."
9,maintenance_tips,complete_upfront,single_turn,cooperative,"(maintenance_tips, complete_upfront, single_tu..."

In [10]:
df[df['interaction_pattern'] == 'multi_turn_linear']

,primary_intent,completeness,interaction_pattern,user_behavior,tuple
1,product_inquiry,partial_info,multi_turn_linear,conversational,"(product_inquiry, partial_info, multi_turn_lin..."
4,policy_question,complete_upfront,multi_turn_linear,cooperative,"(policy_question, complete_upfront, multi_turn..."
5,recall_booking,partial_info,multi_turn_linear,corrective,"(recall_booking, partial_info, multi_turn_line..."
6,book_appointment,complete_upfront,multi_turn_linear,cooperative,"(book_appointment, complete_upfront, multi_tur..."
13,book_appointment,no_info,multi_turn_linear,cooperative,"(book_appointment, no_info, multi_turn_linear,..."
15,shop_info,minimal_info,multi_turn_linear,cooperative,"(shop_info, minimal_info, multi_turn_linear, c..."

### 1.3 Configure Testing Phase

We'll generate synthetic examples in phases:
- **Phase A**: Single-turn conversations (simple query/response)
- **Phase B**: Multi-turn conversations (adaptive user with goal)

Set the phase configuration below:

In [11]:
# Configuration: Run both Phase A and Phase B sequentially
# Phase A: single_turn only (simple, good for starting)
# Phase B: multi-turn patterns (more complex, adaptive user simulation)

print("="*80)
print("RUNNING BOTH PHASES SEQUENTIALLY")
print("="*80)
print("\nPhase A: Single-Turn Conversations")
print("   - Focus: Simple query/response interactions")
print("   - Scenarios: single_turn interaction patterns only")
print("\nPhase B: Multi-Turn Conversations")
print("   - Focus: Complex conversations with adaptive user simulation")
print("   - Scenarios: multi_turn_linear, multi_turn_complex, mixed_intent patterns")
print("="*80 + "\n")

# Separate scenarios by phase
phase_a_scenarios = [s for s in test_scenarios if s['interaction_pattern'] == 'single_turn']
phase_b_scenarios = [s for s in test_scenarios if s['interaction_pattern'] != 'single_turn']

print(f"✓ Phase A scenarios: {len(phase_a_scenarios)}")
print(f"✓ Phase B scenarios: {len(phase_b_scenarios)}")
print(f"✓ Total scenarios: {len(test_scenarios)}")

================================================================================
RUNNING BOTH PHASES SEQUENTIALLY
================================================================================

Phase A: Single-Turn Conversations
   - Focus: Simple query/response interactions
   - Scenarios: single_turn interaction patterns only

Phase B: Multi-Turn Conversations
   - Focus: Complex conversations with adaptive user simulation
   - Scenarios: multi_turn_linear, multi_turn_complex, mixed_intent patterns
================================================================================

✓ Phase A scenarios: 3
✓ Phase B scenarios: 17
✓ Total scenarios: 20

### 1.4 Generate Synthetic Examples

Based on the selected phase, generate appropriate synthetic examples.

In [12]:
# Phase A: Generate simple single-turn queries
def generate_phase_a_examples(scenarios, examples_per_scenario=1):
    """
    Generate simple, realistic single-turn queries for Phase A scenarios.
    
    Args:
        scenarios: List of scenario dictionaries
        examples_per_scenario: Number of example queries to generate per scenario (default: 1)
    
    Returns:
        List of query dictionaries with metadata
    """
    examples = []
    
    for scenario in scenarios:
        for example_num in range(examples_per_scenario):
            # Create a prompt to generate a realistic single-turn query
            query_prompt = f"""Generate a single, realistic user query for a bike shop chatbot.

Scenario details:
- Primary Intent: {scenario['primary_intent']}
- Information Completeness: {scenario['completeness']}
- User Behavior: {scenario['user_behavior']}

Requirements:
- Generate ONE natural language query that a real customer might ask
- Match the primary intent (e.g., shop_info = asking about hours/location)
- Match the completeness level:
  * complete_upfront: Include all necessary details in the query
  * partial_info: Include some but not all details
  * minimal_info: Very basic query with little detail
  * no_info: General question with no specifics
- Use natural, friendly tone for conversational behavior

Return ONLY the user query, nothing else. Make it sound natural and realistic."""

            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are an expert at creating realistic user queries for chatbot testing."},
                    {"role": "user", "content": query_prompt}
                ],
                temperature=0.8
            )
            
            user_query = response.choices[0].message.content.strip()
            
            examples.append({
                'phase': 'A',
                'scenario': scenario,
                'user_query': user_query,
                'expected_mode': scenario['primary_intent']
            })
    
    return examples


# Phase B: Generate multi-turn conversation goals (for future use)
def generate_phase_b_examples(scenarios):
    """
    Generate conversation goals and initial queries for Phase B scenarios.
    These will be used with adaptive user simulation.
    
    Args:
        scenarios: List of scenario dictionaries
    
    Returns:
        List of conversation goal dictionaries with metadata
    """
    examples = []
    
    for scenario in scenarios:
        # Create goal based on intent
        intent = scenario['primary_intent']
        if intent == 'book_appointment':
            goal = "Successfully book a service appointment by providing service type, date, and time"
        elif intent == 'shop_info':
            goal = "Get specific information about shop hours, location, or services"
        elif intent == 'product_inquiry':
            goal = "Learn about specific bikes or accessories and their availability"
        elif intent == 'maintenance_tips':
            goal = "Get practical advice on bike maintenance or care"
        elif intent == 'policy_question':
            goal = "Understand store policies regarding returns, warranties, or delivery"
        elif intent == 'recall_booking':
            goal = "Successfully recall or reference a previously made booking"
        else:
            goal = f"Complete a {intent} interaction successfully"
        
        # Generate initial query
        query_prompt = f"""Generate an initial user query to start a multi-turn conversation with a bike shop chatbot.

Scenario:
- Primary Intent: {scenario['primary_intent']}
- Information Completeness: {scenario['completeness']}
- User Behavior: {scenario['user_behavior']}
- User Goal: {goal}

Generate a realistic opening message that matches the completeness level and behavior.
Return ONLY the initial query, nothing else."""

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are an expert at creating realistic conversation starters."},
                {"role": "user", "content": query_prompt}
            ],
            temperature=0.8
        )
        
        initial_query = response.choices[0].message.content.strip()
        
        examples.append({
            'phase': 'B',
            'scenario': scenario,
            'user_goal': goal,
            'initial_query': initial_query,
            'expected_mode': scenario['primary_intent']
        })
    
    return examples


print("✓ Phase A and Phase B generation functions defined")

✓ Phase A and Phase B generation functions defined

In [13]:
# Generate examples for both phases
all_synthetic_examples = {}

print("\n" + "="*80)
print("GENERATING SYNTHETIC EXAMPLES FOR BOTH PHASES")
print("="*80 + "\n")

# Phase A
print("📍 Phase A: Generating single-turn queries...")
phase_a_examples = generate_phase_a_examples(phase_a_scenarios, examples_per_scenario=2)
all_synthetic_examples['A'] = phase_a_examples
print(f"✓ Generated {len(phase_a_examples)} Phase A single-turn queries\n")

# Save Phase A examples
output_file_a = 'phase_a_synthetic_examples.json'
with open(output_file_a, 'w') as f:
    json.dump({
        'phase': 'A',
        'count': len(phase_a_examples),
        'examples': phase_a_examples
    }, f, indent=2)
print(f"✓ Saved to {output_file_a}\n")

# Phase B
print("📍 Phase B: Generating multi-turn conversation goals...")
phase_b_examples = generate_phase_b_examples(phase_b_scenarios)
all_synthetic_examples['B'] = phase_b_examples
print(f"✓ Generated {len(phase_b_examples)} Phase B conversation goals\n")

# Save Phase B examples
output_file_b = 'phase_b_synthetic_examples.json'
with open(output_file_b, 'w') as f:
    json.dump({
        'phase': 'B',
        'count': len(phase_b_examples),
        'examples': phase_b_examples
    }, f, indent=2)
print(f"✓ Saved to {output_file_b}\n")

print("="*80)
print(f"TOTAL: {len(phase_a_examples) + len(phase_b_examples)} examples generated")
print("="*80)

================================================================================
GENERATING SYNTHETIC EXAMPLES FOR BOTH PHASES
================================================================================

📍 Phase A: Generating single-turn queries...
✓ Generated 6 Phase A single-turn queries

✓ Saved to phase_a_synthetic_examples.json

📍 Phase B: Generating multi-turn conversation goals...
✓ Generated 17 Phase B conversation goals

✓ Saved to phase_b_synthetic_examples.json

================================================================================
TOTAL: 23 examples generated
================================================================================

In [14]:
# Display sample examples from both phases
print("\n" + "="*80)
print("SAMPLE SYNTHETIC EXAMPLES")
print("="*80)

print("\n--- PHASE A SAMPLES ---\n")
for i, example in enumerate(all_synthetic_examples['A'][:3], 1):
    print(f"{i}. Scenario: {example['scenario']['tuple']}")
    print(f"   Query: \"{example['user_query']}\"")
    print()

print("\n--- PHASE B SAMPLES ---\n")
for i, example in enumerate(all_synthetic_examples['B'][:3], 1):
    print(f"{i}. Scenario: {example['scenario']['tuple']}")
    print(f"   Goal: {example['user_goal']}")
    print(f"   Initial Query: \"{example['initial_query']}\"")
    print()

================================================================================
SAMPLE SYNTHETIC EXAMPLES
================================================================================

--- PHASE A SAMPLES ---

1. Scenario: (shop_info, complete_upfront, single_turn, cooperative)
   Query: ""Hi there! Could you please tell me your store hours and location? I'm planning to visit soon and want to make sure I have the right details. Thanks!""

2. Scenario: (shop_info, complete_upfront, single_turn, cooperative)
   Query: ""Hi there! Could you please tell me your store hours and if you're open on weekends? I'm planning a visit soon. Thanks!""

3. Scenario: (what_can_you_do, no_info, single_turn, conversational)
   Query: "Hey there! What kind of things can you help me with?"


--- PHASE B SAMPLES ---

1. Scenario: (product_inquiry, partial_info, multi_turn_linear, conversational)
   Goal: Learn about specific bikes or accessories and their availability
   Initial Query: "Hi there! I'm looking to find out more about mountain bikes, specifically those suitable for beginners. Do you have any models in stock?"

2. Scenario: (book_appointment, minimal_info, multi_turn_complex, cooperative)
   Goal: Successfully book a service appointment by providing service type, date, and time
   Initial Query: ""Hi, I'd like to book an appointment for my bike. Can you help with that?""

3. Scenario: (maintenance_tips, no_info, multi_turn_complex, distracted)
   Goal: Get practical advice on bike maintenance or care
   Initial Query: "Hey there! I'm thinking about doing some maintenance on my bike but not really sure where to start. Any tips or advice you could share?"

## Part 2: Error Analysis - Running Simulations

We'll use the `synthetic_examples` generated in Part 1 based on the `TESTING_PHASE` configuration.

In [15]:
# Verify we have synthetic examples to test
if 'all_synthetic_examples' not in locals() or not all_synthetic_examples:
    raise ValueError("No synthetic examples found. Please run Part 1 first to generate examples.")

print("✓ Loaded synthetic examples from Part 1")
print(f"  Phase A examples: {len(all_synthetic_examples['A'])}")
print(f"  Phase B examples: {len(all_synthetic_examples['B'])}")
print(f"  Total examples: {len(all_synthetic_examples['A']) + len(all_synthetic_examples['B'])}")

✓ Loaded synthetic examples from Part 1
  Phase A examples: 6
  Phase B examples: 17
  Total examples: 23

### Test Execution Functions

We define two test functions:
- **Phase A** (`run_single_turn_test`): Tests simple one-query-one-response interactions
- **Phase B** (`run_multi_turn_test`): Uses DeepEval to simulate realistic multi-turn conversations where the synthetic user adapts based on bot responses

**Note**: In Phase B, a "turn" means one complete user-assistant exchange (user sends a message, bot responds).

In [16]:
# Import Burr application
import sys
sys.path.append('..')

from application import application, TERMINAL_ACTIONS
import asyncio

print("✓ Burr application imported successfully")

✓ Burr application imported successfully

In [17]:
# Function to run a single-turn test (Phase A)
async def run_single_turn_test(example, test_id):
    """
    Run a single-turn test: submit query, get bot response.
    
    Args:
        example: Dictionary with scenario and user_query from synthetic_examples
        test_id: Unique identifier for this test
    
    Returns:
        Dictionary with test results
    """
    # Create fresh Burr application instance
    app = application(app_id=f"test_{test_id}")
    
    user_query = example['user_query']
    scenario = example['scenario']
    
    result = {
        'test_id': test_id,
        'scenario': scenario,
        'user_query': user_query,
        'bot_response': None,
        'action_taken': None,
        'state_snapshot': None,
        'success': False,
        'error': None
    }
    
    try:
        # Submit query to bot
        action, streaming_container = await app.astream_result(
            halt_after=TERMINAL_ACTIONS,
            inputs={"query": user_query}
        )
        
        # Collect streaming response
        response_parts = []
        async for item in streaming_container:
            response_parts.append(item.get('delta', ''))
        
        bot_response = ''.join(response_parts)
        
        # Get final state
        final_result, state = await streaming_container.get()
        
        # Update result
        result['bot_response'] = bot_response
        result['action_taken'] = action.name
        result['state_snapshot'] = {
            'mode': state.get('mode'),
            'in_appointment_flow': state.get('in_appointment_flow'),
            'appointment_data': state.get('appointment_data'),
            'safe': state.get('safe')
        }
        result['success'] = True
        
    except Exception as e:
        result['error'] = str(e)
    
    return result

print("✓ Function defined: run_single_turn_test()")

✓ Function defined: run_single_turn_test()

In [18]:
async def run_multi_turn_test(example, test_id):
    """
    Run a multi-turn test using DeepEval's ConversationSimulator.
    Generates synthetic conversations based on scenario and user goal.
    
    Note: A "turn" = one user-assistant exchange (user message + bot response).
    
    Args:
        example: Dictionary with scenario, user_goal, and initial_query
        test_id: Unique identifier for this test
    
    Returns:
        Dictionary with test results including conversation turns
    """
    from deepeval.simulator import ConversationSimulator
    from deepeval.dataset import ConversationalGolden
    from deepeval.test_case import Turn
    from typing import List
    
    # Cache for maintaining conversation state
    _app_cache = {}
    
    # Model callback that wraps the Burr application
    async def burr_model_callback(input: str, turns: List[Turn], thread_id: str) -> Turn:
        """Wraps Burr app so DeepEval can interact with it."""
        # Reuse existing app for this conversation or create new one
        if thread_id not in _app_cache:
            _app_cache[thread_id] = application(app_id=f"{test_id}_{thread_id}")
        
        app = _app_cache[thread_id]
        
        _, streaming_container = await app.astream_result(
            halt_after=TERMINAL_ACTIONS,
            inputs={"query": input}
        )
        
        # Extract response from Burr's state
        _, state = await streaming_container.get()
        bot_message = state["response"]["content"]
        
        return Turn(role="assistant", content=bot_message)
    
    scenario = example['scenario']
    
    # Create scenario description from tuple dimensions
    scenario_desc = f"A user with {scenario['user_behavior']} behavior wants to {scenario['primary_intent'].replace('_', ' ')}."
    
    # Generate expected outcome based on intent
    intent = scenario['primary_intent']
    if intent == 'book_appointment':
        expected_outcome = "The bot should successfully collect service type, date, and time, then confirm the booking."
    elif intent == 'shop_info':
        expected_outcome = "The bot should provide accurate information about shop hours, location, or services."
    elif intent == 'product_inquiry':
        expected_outcome = "The bot should provide information about bikes or accessories and their availability."
    elif intent == 'maintenance_tips':
        expected_outcome = "The bot should provide helpful maintenance advice."
    elif intent == 'policy_question':
        expected_outcome = "The bot should clearly explain the relevant store policy."
    elif intent == 'recall_booking':
        expected_outcome = "The bot should help the user recall or reference their previous booking."
    else:
        expected_outcome = f"The bot should successfully handle the {intent.replace('_', ' ')} request."
    
    # User description based on behavior
    user_desc = scenario['user_behavior'].replace('_', ' ').capitalize() + " user"
    
    # Create ConversationalGolden
    golden = ConversationalGolden(
        scenario=scenario_desc,
        expected_outcome=expected_outcome,
        user_description=user_desc
    )
    
    result = {
        'test_id': test_id,
        'scenario': scenario,
        'user_goal': example.get('user_goal', ''),
        'initial_query': example.get('initial_query', ''),
        'turns': [],
        'conversation': [],
        'success': False,
        'error': None
    }
    
    try:
        # Create simulator
        simulator = ConversationSimulator(model_callback=burr_model_callback)
        
        # Simulate the conversation (max_user_simulations=5 means up to 5 user-assistant exchanges)
        test_cases = simulator.simulate(
            conversational_goldens=[golden],
            max_user_simulations=5
        )
        
        # Extract conversation from test case
        if test_cases:
            test_case = test_cases[0]
            result['turns'] = [
                {'role': turn.role, 'content': turn.content}
                for turn in test_case.turns
            ]
            result['conversation'] = result['turns']  # For backward compatibility
            result['success'] = True
        
        # Clear app cache for this test
        _app_cache.clear()
        
    except Exception as e:
        result['error'] = str(e)
    
    return result

print("✓ Function defined: run_multi_turn_test()")

✓ Function defined: run_multi_turn_test()

In [19]:
# Run tests for both phases sequentially
all_test_results = {}

print("\n" + "="*80)
print("RUNNING ALL TESTS - BOTH PHASES")
print("="*80 + "\n")

# ==================== PHASE A ====================
print("╔" + "="*78 + "╗")
print("║" + " "*25 + "PHASE A: SINGLE-TURN TESTS" + " "*27 + "║")
print("╚" + "="*78 + "╝\n")

TESTING_PHASE = "A"
phase_a_examples = all_synthetic_examples['A']
print(f"Starting Phase A with {len(phase_a_examples)} single-turn tests...\n")

phase_a_results = []
for idx, example in enumerate(phase_a_examples, 1):
    test_id = f"A{idx:03d}"
    print(f"[{idx}/{len(phase_a_examples)}] Running test {test_id}: {example['scenario']['primary_intent']}...", end=" ", flush=True)
    
    result = await run_single_turn_test(example, test_id)
    phase_a_results.append(result)
    
    if result['success']:
        print(f"✓ ({result['action_taken']})")
    else:
        print(f"✗ Error: {result['error']}")

all_test_results['A'] = phase_a_results

print(f"\n✓ Phase A Complete: {sum(1 for r in phase_a_results if r['success'])}/{len(phase_a_results)} successful\n")

# ==================== PHASE B ====================
print("╔" + "="*78 + "╗")
print("║" + " "*24 + "PHASE B: MULTI-TURN TESTS" + " "*28 + "║")
print("╚" + "="*78 + "╝\n")

TESTING_PHASE = "B"
phase_b_examples = all_synthetic_examples['B']
print(f"Starting Phase B with {len(phase_b_examples)} multi-turn tests (DeepEval simulation)...\n")

phase_b_results = []
for idx, example in enumerate(phase_b_examples, 1):
    test_id = f"B{idx:03d}"
    print(f"[{idx}/{len(phase_b_examples)}] Running test {test_id}: {example['scenario']['primary_intent']}...", end=" ", flush=True)
    
    result = await run_multi_turn_test(example, test_id)
    phase_b_results.append(result)
    
    if result['success']:
        # Count user-assistant exchanges (turns), not total messages
        num_exchanges = len([t for t in result['turns'] if t['role'] == 'user'])
        print(f"✓ ({num_exchanges} turns)")
    else:
        print(f"✗ Error: {result['error']}")

all_test_results['B'] = phase_b_results

print(f"\n✓ Phase B Complete: {sum(1 for r in phase_b_results if r['success'])}/{len(phase_b_results)} successful\n")

# ==================== SUMMARY ====================
print("="*80)
print("OVERALL TEST SUMMARY")
print("="*80)
total_tests = len(phase_a_results) + len(phase_b_results)
total_success = sum(1 for r in phase_a_results if r['success']) + sum(1 for r in phase_b_results if r['success'])
print(f"Phase A: {sum(1 for r in phase_a_results if r['success'])}/{len(phase_a_results)} successful")
print(f"Phase B: {sum(1 for r in phase_b_results if r['success'])}/{len(phase_b_results)} successful")

print(f"TOTAL:   {total_success}/{total_tests} successful")
print("="*80)

================================================================================
RUNNING ALL TESTS - BOTH PHASES
================================================================================

╔==============================================================================╗
║                         PHASE A: SINGLE-TURN TESTS                           ║
╚==============================================================================╝

Starting Phase A with 6 single-turn tests...

[1/6] Running test A001: shop_info... ✓ (shop_info)
[2/6] Running test A002: shop_info... ✓ (shop_info)
[3/6] Running test A003: what_can_you_do... ✓ (what_can_you_do)
[4/6] Running test A004: what_can_you_do... ✓ (what_can_you_do)
[5/6] Running test A005: maintenance_tips... ✓ (maintenance_tips)
[6/6] Running test A006: maintenance_tips... ✓ (maintenance_tips)

✓ Phase A Complete: 6/6 successful

╔==============================================================================╗
║                        PHASE B: MULTI-TURN TESTS                            ║
╚==============================================================================╝

Starting Phase B with 17 multi-turn tests (DeepEval simulation)...

[1/17] Running test B001: product_inquiry...

Overriding of current TracerProvider is not allowed

Output()

✓ (4 turns)
[2/17] Running test B002: book_appointment...

Output()

✓ (5 turns)
[3/17] Running test B003: maintenance_tips...

Output()

✓ (1 turns)
[4/17] Running test B004: policy_question...

Output()

✓ (2 turns)
[5/17] Running test B005: recall_booking...

Output()

✓ (5 turns)
[6/17] Running test B006: book_appointment...

Output()

✓ (5 turns)
[7/17] Running test B007: product_inquiry...

Output()

✓ (3 turns)
[8/17] Running test B008: book_appointment...

Output()

✓ (5 turns)
[9/17] Running test B009: policy_question...

Output()

✓ (2 turns)
[10/17] Running test B010: recall_booking...

Output()

✓ (5 turns)
[11/17] Running test B011: book_appointment...

Output()

✓ (5 turns)
[12/17] Running test B012: what_can_you_do...

Output()

✓ (1 turns)
[13/17] Running test B013: shop_info...

Output()

✓ (3 turns)
[14/17] Running test B014: book_appointment...

Output()

✓ (4 turns)
[15/17] Running test B015: product_inquiry...

Output()

✓ (3 turns)
[16/17] Running test B016: recall_booking...

Output()

✓ (5 turns)
[17/17] Running test B017: book_appointment...

Output()

✓ (5 turns)

✓ Phase B Complete: 17/17 successful

================================================================================
OVERALL TEST SUMMARY
================================================================================
Phase A: 6/6 successful
Phase B: 17/17 successful
TOTAL:   23/23 successful
================================================================================

### Running All Tests

This cell executes both testing phases sequentially:
1. **Phase A** runs each single-turn query against the chatbot and captures the response
2. **Phase B** uses DeepEval's conversation simulator to create realistic multi-turn dialogs

Progress is displayed in real-time so you can monitor the testing.

In [20]:
# Display sample results from both phases
print("\n" + "="*80)
print("SAMPLE TEST RESULTS")
print("="*80)

print("\n--- PHASE A SAMPLES (Single-Turn) ---\n")
for i, result in enumerate(all_test_results['A'], 1):
    print(f"Test {result['test_id']}")
    print(f"Scenario: {result['scenario']['tuple']}")
    print(f"User Query: \"{result['user_query']}\"")
    print(f"Bot Response: {result['bot_response']}")
    print(f"Mode: {result['state_snapshot']['mode']}")
    print("-"*80 + "\n")

print("--- PHASE B SAMPLES (Multi-Turn Conversations) ---\n")
for i, result in enumerate(all_test_results['B'], 1):
    print(f"Test {result['test_id']}")
    print(f"Scenario: {result['scenario']['tuple']}")
    print(f"Goal: {result['user_goal']}")
    
    # Group messages into user-assistant exchanges (turns)
    # Each turn = 1 user message + 1 assistant response
    turns = result['turns']
    num_exchanges = len([t for t in turns if t['role'] == 'user'])
    print(f"Conversation ({num_exchanges} turns):\n")
    
    # Display conversation showing each user-assistant exchange as one "turn"
    exchange_num = 0
    i = 0
    while i < len(turns):
        if turns[i]['role'] == 'user':
            exchange_num += 1
            user_content = turns[i]['content']
            print(f"  Turn {exchange_num}:")
            print(f"    User: {user_content}")
            
            # Look for assistant response
            if i + 1 < len(turns) and turns[i + 1]['role'] == 'assistant':
                assistant_content = turns[i + 1]['content']
                print(f"    Assistant: {assistant_content}")
                i += 2
            else:
                print(f"    Assistant: [no response]")
                i += 1
        else:
            i += 1
    
    print("-"*80 + "\n")

================================================================================
SAMPLE TEST RESULTS
================================================================================

--- PHASE A SAMPLES (Single-Turn) ---

Test A001
Scenario: (shop_info, complete_upfront, single_turn, cooperative)
User Query: ""Hi there! Could you please tell me your store hours and location? I'm planning to visit soon and want to make sure I have the right details. Thanks!""
Bot Response: Absolutely! JO's Bike Shop is located at 456 Pedal Lane, Portland, OR 97201. We're open 7 days a week with hours ranging from 9:00 AM to 7:00 PM on weekdays and extended hours on Thursdays and Fridays. Can't wait to have you visit us and chat about all things bikes! 🚴‍♂️
Mode: shop_info
--------------------------------------------------------------------------------

Test A002
Scenario: (shop_info, complete_upfront, single_turn, cooperative)
User Query: ""Hi there! Could you please tell me your store hours and if you're open on weekends? I'm planning a visit soon. Thanks!""
Bot Response: Absolutely, we'd love to have you visit JO's Bike Shop! We're open 7 days a week. Our hours are Monday to Wednesday 9:00 AM - 6:00 PM, Thursday and Friday 9:00 AM - 7:00 PM, Saturday 8:00 AM - 5:00 PM, and Sunday 10:00 AM - 4:00 PM. Can't wait to see you roll in! 🚴‍♂️
Mode: shop_info
--------------------------------------------------------------------------------

Test A003
Scenario: (what_can_you_do, no_info, single_turn, conversational)
User Query: "Hey there! What kind of things can you help me with?"
Bot Response: I'm here to help you with JO's Bike Shop! I can assist you with:

• **Shop Information** - Opening hours, location, and contact details

• **Product Inquiries** - Available bikes, accessories, and product availability

• **Service Appointments** - Booking bike service and repairs

• **Maintenance Tips** - Advice on keeping your bike in top condition

• **Shop Policies** - Questions about returns, warranties, and delivery

How can I help you today?
Mode: what_can_you_do
--------------------------------------------------------------------------------

Test A004
Scenario: (what_can_you_do, no_info, single_turn, conversational)
User Query: "Hey there! What all can you help me with?"
Bot Response: I'm here to help you with JO's Bike Shop! I can assist you with:

• **Shop Information** - Opening hours, location, and contact details

• **Product Inquiries** - Available bikes, accessories, and product availability

• **Service Appointments** - Booking bike service and repairs

• **Maintenance Tips** - Advice on keeping your bike in top condition

• **Shop Policies** - Questions about returns, warranties, and delivery

How can I help you today?
Mode: what_can_you_do
--------------------------------------------------------------------------------

Test A005
Scenario: (maintenance_tips, complete_upfront, single_turn, cooperative)
User Query: ""Hi there! I'm planning to tune up my bike this weekend and could really use some tips on how to properly clean and lubricate the chain. Could you guide me through the process or provide any other maintenance advice to keep my bike running smoothly?""
Bot Response: Sure! To clean and lubricate your chain, start by wiping it down with a rag to remove dirt and debris. Then, apply chain lubricant and wipe off any excess. Additionally, regularly check tire pressure, brake pads, and overall cleanliness to ensure your bike runs smoothly.
Mode: maintenance_tips
--------------------------------------------------------------------------------

Test A006
Scenario: (maintenance_tips, complete_upfront, single_turn, cooperative)
User Query: "Hi there! I'm planning to do some maintenance on my road bike this weekend. Can you give me some tips on how to properly clean and lubricate the chain, and check the tire pressure? Thanks!"
Bot Response: Sure! To clean your chain, use a degreaser and a chain cleaning tool before applying a lubricant. Check your tire pressure with a pump and gauge, and ensure it matches the manufacturer's recommendations for optimal performance.
Mode: maintenance_tips
--------------------------------------------------------------------------------

--- PHASE B SAMPLES (Multi-Turn Conversations) ---

Test B001
Scenario: (product_inquiry, partial_info, multi_turn_linear, conversational)
Goal: Learn about specific bikes or accessories and their availability
Conversation (4 turns):

  Turn 1:
    User: Hi there! I’m interested in learning more about one of your products—could you help me with some details?
    Assistant: Of course! We'd be happy to help. Please let us know which specific product you're interested in learning more about so we can provide you with the details you need. Feel free to reach out to us at (503) 555-BIKE or info@josbikeshop.com for more information.
  Turn 2:
    User: Thanks! I’m interested in your electric bikes—could you tell me more about the models you offer?
    Assistant: Certainly! We offer a range of electric bikes with different features such as pedal-assist, throttle control, and various battery capacities. Each model is designed for different types of riding preferences and terrain. Feel free to contact us at (503) 555-BIKE or info@josbikeshop.com for more detailed information on our electric bike options.
  Turn 3:
    User: That sounds great! Could you share a list of your electric bike models and their main features?
    Assistant: Sure! We offer a variety of electric bike models with features such as pedal-assist, throttle control, different battery capacities, and varying designs for different riding preferences. Please contact us at (503) 555-BIKE or info@josbikeshop.com for a detailed list of our electric bike models and their specific features.
  Turn 4:
    User: Is there a place online where I can view the models and compare their features, or could you send me a brochure?
    Assistant: Yes, you can view our electric bike models and compare their features on our website at www.josbikeshop.com. If you prefer a brochure, please contact us at (503) 555-BIKE or info@josbikeshop.com, and we'd be happy to send one to you.
--------------------------------------------------------------------------------

Test B002
Scenario: (book_appointment, minimal_info, multi_turn_complex, cooperative)
Goal: Successfully book a service appointment by providing service type, date, and time
Conversation (5 turns):

  Turn 1:
    User: Hello! I’d like to book an appointment, please. Could you help me with the available times?
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 2:
    User: I’d like to schedule a tune-up, please. What days and times are available?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 3:
    User: Next Friday would be perfect for me—do you have any openings then?
    Assistant: Great! I have you down for a tune-up. What time would you prefer? We have morning (8am-12pm) and afternoon (1pm-5pm) slots available.
  Turn 4:
    User: Afternoon would be best—could I book a slot around 2pm?
    Assistant: Perfect! Let me confirm your appointment:

• Service: tune-up
• Date: next Friday
• Time: afternoon

Does this look correct? I can book this for you now!
  Turn 5:
    User: Yes, that looks great—please go ahead and book it for me. Thank you!
    Assistant: Excellent! Your appointment has been booked. We'll see you then! Is there anything else I can help you with?
--------------------------------------------------------------------------------

Test B003
Scenario: (maintenance_tips, no_info, multi_turn_complex, distracted)
Goal: Get practical advice on bike maintenance or care
Conversation (1 turns):

  Turn 1:
    User: Hey, sorry if I seem a bit all over the place, but do you have any quick tips for keeping things in good shape? I keep forgetting about maintenance stuff.
    Assistant: No worries! Remember to regularly check tire pressure, lubricate the chain, and clean your bike after riding in wet conditions to ensure everything stays in good shape. If you have any specific questions, feel free to reach out to the shop for more assistance.
--------------------------------------------------------------------------------

Test B004
Scenario: (policy_question, complete_upfront, multi_turn_linear, cooperative)
Goal: Understand store policies regarding returns, warranties, or delivery
Conversation (2 turns):

  Turn 1:
    User: Hi there! I have a question about a specific policy and was hoping you could help clarify a few things for me.
    Assistant: Of course! Please feel free to ask your question about our policies regarding returns, warranties, or delivery. We are here to assist you in any way we can.
  Turn 2:
    User: Thank you! I wanted to know more about your return policy—specifically, how long do I have to return an item after purchase?
    Assistant: Our return policy allows for items to be returned within 30 days of purchase for a full refund or exchange. Please contact us at (503) 555-BIKE or info@josbikeshop.com for further assistance with returns.
--------------------------------------------------------------------------------

Test B005
Scenario: (recall_booking, partial_info, multi_turn_linear, corrective)
Goal: Successfully recall or reference a previously made booking
Conversation (5 turns):

  Turn 1:
    User: Hi, I’d like to check the details of a booking I made earlier. Can you help me recall it?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 2:
    User: Actually, I already made a booking earlier—could you double-check if it's under my name or email?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 3:
    User: I’m sure I made a booking—can you please check your records again using my email address?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 4:
    User: I understand, but I definitely made a booking—can you please check your system one more time for any record under my name or email?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 5:
    User: I’m certain I made a booking—can you please escalate this or check with someone who can access all records?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
--------------------------------------------------------------------------------

Test B006
Scenario: (book_appointment, complete_upfront, multi_turn_linear, cooperative)
Goal: Successfully book a service appointment by providing service type, date, and time
Conversation (5 turns):

  Turn 1:
    User: Hi there! I’d like to book an appointment and was hoping you could help me with the process.
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 2:
    User: I’d like to schedule a tune-up, please. What dates and times are available?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 3:
    User: Next Friday would be perfect for me—do you have any openings then?
    Assistant: Great! I have you down for a tune-up. What time would you prefer? We have morning (8am-12pm) and afternoon (1pm-5pm) slots available.
  Turn 4:
    User: Afternoon would be best—can I book a slot around 2pm?
    Assistant: Perfect! Let me confirm your appointment:

• Service: tune-up
• Date: next Friday
• Time: around 2pm

Does this look correct? I can book this for you now!
  Turn 5:
    User: Yes, that looks perfect—please go ahead and book it for me. Thank you!
    Assistant: Excellent! Your appointment has been booked. We'll see you then! Is there anything else I can help you with?
--------------------------------------------------------------------------------

Test B007
Scenario: (product_inquiry, partial_info, mixed_intent, distracted)
Goal: Learn about specific bikes or accessories and their availability
Conversation (3 turns):

  Turn 1:
    User: Hey, I was wondering if you could tell me more about one of your products? Sorry, I might get a bit sidetracked, but I’m interested in learning more.
    Assistant: Of course! I'd be happy to provide more information about our products. Just let me know which specific bike or accessory you're interested in, and I can give you more details. Feel free to ask any questions you have!
  Turn 2:
    User: Oh right, I was looking at your mountain bikes—do you have one that's good for beginners? Also, sorry if I jump around a bit!
    Assistant: No worries at all! For beginners, I recommend our entry-level mountain bike, the Trailblazer. It's durable, easy to maneuver, and has all the features you need to get started on your off-road adventures. Feel free to ask any more questions you have!
  Turn 3:
    User: That sounds great! Oh, and does it come in different colors? Sorry, I just remembered I also wanted to ask about helmets.
    Assistant: Yes, the Trailblazer mountain bike comes in a variety of colors to suit your preference. As for helmets, we have a range of options available for different styles and sizes to ensure safety and comfort on your rides. Feel free to ask if you have any more questions!
--------------------------------------------------------------------------------

Test B008
Scenario: (book_appointment, partial_info, mixed_intent, distracted)
Goal: Successfully book a service appointment by providing service type, date, and time
Conversation (5 turns):

  Turn 1:
    User: Hey, I need to book an appointment but I keep getting sidetracked. Can you help me set one up quickly?
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 2:
    User: Oh right, I need a tune-up for my bike—can you just pick the earliest available slot for me?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 3:
    User: Uh, sorry, I totally forgot to check my calendar—can you just book the soonest one and let me know?
    Assistant: Great! I have you down for a tune-up. What time would you prefer? We have morning (8am-12pm) and afternoon (1pm-5pm) slots available.
  Turn 4:
    User: Whichever is sooner is fine—just book it and let me know, thanks!
    Assistant: Perfect! Let me confirm your appointment:

• Service: tune-up
• Date: soonest
• Time: sooner

Does this look correct? I can book this for you now!
  Turn 5:
    User: Yes, that's perfect—please go ahead and book it for me!
    Assistant: Excellent! Your appointment has been booked. We'll see you then! Is there anything else I can help you with?
--------------------------------------------------------------------------------

Test B009
Scenario: (policy_question, minimal_info, multi_turn_complex, cooperative)
Goal: Understand store policies regarding returns, warranties, or delivery
Conversation (2 turns):

  Turn 1:
    User: Hi there! I have a question about a policy and was hoping you could help clarify a few things for me.
    Assistant: Of course! Please feel free to ask your questions about our shop policies regarding returns, warranties, or delivery. You can reach us at (503) 555-BIKE or info@josbikeshop.com for more information. Thank you!
  Turn 2:
    User: Thanks! Could you explain your return policy in more detail, especially for items purchased online?
    Assistant: Our shop has a 30-day return policy for online purchases, provided the item is unused and in its original packaging. Please contact us at (503) 555-BIKE or info@josbikeshop.com for specific instructions on returning your item.
--------------------------------------------------------------------------------

Test B010
Scenario: (recall_booking, no_info, multi_turn_complex, cooperative)
Goal: Successfully recall or reference a previously made booking
Conversation (5 turns):

  Turn 1:
    User: Hi there! I’d like to check the details of a booking I made earlier. Could you help me with that?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 2:
    User: I actually made the booking a few days ago—could you check if you have it on file under my name?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 3:
    User: Maybe I used a different email or phone number—can I provide those details to help you find my booking?
    Assistant: I don't see any completed bookings in our current conversation. Would you like to book an appointment?
  Turn 4:
    User: Yes, let's go ahead and book an appointment then. What information do you need from me?
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 5:
    User: I’d like to book a tune-up, please—what dates and times are available?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
--------------------------------------------------------------------------------

Test B011
Scenario: (book_appointment, no_info, multi_turn_linear, cooperative)
Goal: Successfully book a service appointment by providing service type, date, and time
Conversation (5 turns):

  Turn 1:
    User: Hi there! I’d like to book an appointment and was hoping you could help me with the process.
    Assistant: What type of service do you need? We offer tune-ups, repairs, full services, and custom work.
  Turn 2:
    User: I’d like to schedule a tune-up, please. What dates and times are available?
    Assistant: Great! I have you down for a tune-up. What date works best for you?
  Turn 3:
    User: Next Friday would be perfect for me—do you have any openings then?
    Assistant: Great! I have you down for a tune-up. What time would you prefer? We have morning (8am-12pm) and afternoon (1pm-5pm) slots available.
  Turn 4:
    User: Afternoon would be best—can I book a slot around 2pm?
    Assistant: Perfect! Let me confirm your appointment:

• Service: tune-up
• Date: next Friday
• Time: afternoon

Does this look correct? I can book this for you now!
  Turn 5:
    User: Yes, that looks great—please go ahead and book it for me. Thank you!
    Assistant: Excellent! Your appointment has been booked. We'll see you then! Is there anything else I can help you with?
--------------------------------------------------------------------------------

Test B012
Scenario: (what_can_you_do, partial_info, mixed_intent, corrective)
Goal: Complete a what_can_you_do interaction successfully
Conversation (1 turns):

  Turn 1:
    User: Hi there! I’m curious about what you can help me with—could you tell me a bit about what you can do?
    Assistant: I'm here to help you with JO's Bike Shop! I can assist you with:

• **Shop Information** - Opening hours, location, and contact details

• **Product Inquiries** - Available bikes, accessories, and product availability

• **Service Appointments** - Booking bike service and repairs

• **Maintenance Tips** - Advice on keeping your bike in top condition

• **Shop Policies** - Questions about returns, warranties, and delivery

How can I help you today?
--------------------------------------------------------------------------------

Test B013
Scenario: (shop_info, minimal_info, multi_turn_linear, cooperative)
Goal: Get specific information about shop hours, location, or services
Conversation (3 turns):

  Turn 1:
    User: Hi there! I’m interested in doing some shopping and would love some information or tips to get started. Could you help me out?

In [21]:
# Save test results for both phases
print("\n" + "="*80)
print("SAVING RESULTS")
print("="*80 + "\n")

for phase in ['A', 'B']:
    results = all_test_results[phase]
    
    output_data = {
        'metadata': {
            'phase': phase,
            'description': f'Phase {phase} conversation tests',
            'timestamp': pd.Timestamp.now().isoformat(),
            'total_tests': len(results),
            'successful_tests': sum(1 for r in results if r['success'])
        },
        'results': results
    }
    
    output_filename = f'phase_{phase.lower()}_results.json'
    with open(output_filename, 'w') as f:
        json.dump(output_data, f, indent=2)
    
    print(f"✓ Phase {phase}: Saved to {output_filename}")
    print(f"  Total tests: {len(results)}")
    print(f"  Successful: {sum(1 for r in results if r['success'])}")
    print(f"  Failed: {sum(1 for r in results if not r['success'])}\n")

print("="*80)
print("✓ All results saved successfully")
print("="*80)

================================================================================
SAVING RESULTS
================================================================================

✓ Phase A: Saved to phase_a_results.json
  Total tests: 6
  Successful: 6
  Failed: 0

✓ Phase B: Saved to phase_b_results.json
  Total tests: 17
  Successful: 17
  Failed: 0

================================================================================
✓ All results saved successfully
================================================================================

### Saving Results

We save two types of files:
- **JSON files** (`phase_a_results.json`, `phase_b_results.json`): Complete raw data with full conversations
- **CSV files** (`phase_a_analysis.csv`, `phase_b_analysis.csv`): Structured format for manual open coding analysis

In [23]:
# Create analysis CSV for open coding (both phases)
print("\n" + "="*80)
print("CREATING ANALYSIS CSVs")
print("="*80 + "\n")

for phase in ['A', 'B']:
    results = all_test_results[phase]
    analysis_rows = []
    
    for result in results:
        scenario = result['scenario']
        
        # Phase A has user_query, Phase B has initial_query and user_goal
        if phase == 'A':
            user_input = result['user_query']
            bot_preview = result['bot_response'][:200] if result['bot_response'] else ''
        else:  # Phase B
            user_input = result.get('initial_query', '')
            # For Phase B, count user-assistant exchanges (turns), not total messages
            turns_list = result.get('turns', [])
            num_exchanges = len([t for t in turns_list if t['role'] == 'user'])
            bot_preview = f"Goal: {result.get('user_goal', '')} | Turns: {num_exchanges}"
        
        row = {
            'Trace_ID': result['test_id'],
            'Phase': phase,
            'Scenario_Tuple': scenario['tuple'],
            'Primary_Intent': scenario['primary_intent'],
            'Completeness': scenario['completeness'],
            'Interaction_Pattern': scenario['interaction_pattern'],
            'User_Behavior': scenario['user_behavior'],
            'User_Query': user_input,
            'Bot_Response_Preview': bot_preview,
            'Action_Taken': result.get('action_taken', ''),
            'Mode_Detected': result['state_snapshot']['mode'] if result.get('state_snapshot') else '',
            'Success': 1 if result['success'] else 0,
            'Error': result['error'] or '',
            'Open_Code_Notes': '',  # For manual analysis
            'Overall_Success': '',  # 0=failed, 1=partial, 2=success (to fill manually)
        }
        analysis_rows.append(row)
    
    analysis_df = pd.DataFrame(analysis_rows)
    csv_filename = f'phase_{phase.lower()}_analysis.csv'
    analysis_df.to_csv(csv_filename, index=False)
    
    print(f"✓ Phase {phase}: Created {csv_filename} ({len(analysis_rows)} rows)\n")

print("="*80)

print("✓ All analysis CSVs created")
print("="*80)

================================================================================
CREATING ANALYSIS CSVs
================================================================================

✓ Phase A: Created phase_a_analysis.csv (6 rows)

✓ Phase B: Created phase_b_analysis.csv (17 rows)

================================================================================
✓ All analysis CSVs created
================================================================================

### Testing Summary

**Completed:**
- ✅ Used synthetic examples from Part 1 based on TESTING_PHASE configuration
- ✅ Ran chatbot against all generated queries
- ✅ Captured bot responses and state information
- ✅ Saved results to `phase_{phase}_results.json` (detailed)
- ✅ Created `phase_{phase}_analysis.csv` for open coding

**Files Created:**
- `phase_{phase}_results.json` - Complete test results with full bot responses
- `phase_{phase}_analysis.csv` - Spreadsheet ready for open coding analysis

**Next Steps:**
1. Review results in Burr UI: `burr` (look for traces starting with `phase_{phase}_`)
2. Perform open coding: Fill in `Open_Code_Notes` column in the CSV
3. After current phase analysis is complete, change TESTING_PHASE in Part 1 and repeat